### ISSUE TITLE
handle FeatureLayers in ONDEMAND mode

### ISSUE THREAD

**Issue by jabadia** [Esri/offline-editor-js#173]
From jrgittyup: When using MODE_ONDEMAND and the user extends a feature service with the offline libraries, and when the application is set to offline mode, prevent the application from attempting to access the network for that feature service and have it find the features solely out of what has been downloaded. Going back online would resume normal MODE_ONDEMAND functionality.

**Comment by andygup** [comment]
Based on several conversations yesterday, there are currently two potential work-arounds for this issue for others who may be interested. 

Additional background: MODE_ONDEMAND is used when you want to limit the features that are being returned after a pan or zoom event. The library currently only works in SNAPSHOT mode where it will return all features in the feature layer or it will honor a [DefinitionExpression](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#defaultdefinitionexpression) or [TimeDefinition](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#settimedefinition).

**Approach 1.** You can break up feature services containing many features (100's of thousands or more) into smaller geographic extents. The edits library works with multiple feature layers.

**Approach 2.** You can [Query](https://developers.arcgis.com/javascript/jsapi/query-amd.html) a specific geographic area. Then use that data to create a feature collection. Then finally create a feature layer using the [feature collection](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#featurelayer2). The edits library overrides the ArcGIS JS API functionality so you can ignore the built-in behavior listed in the API reference page.
