### ISSUE TITLE
Offline Symbology Doesn't Display, Only Phantom Symbols

### ISSUE THREAD

**Issue by cy-nwg** [Esri/offline-editor-js#280]
When resuming an app in offline mode, the feature layer symbology does not render on the map, only the phantom symbols display.

Steps to reproduce (Chrome):

1. Load feature layer into map.
2. Go Offline (features stored in local storage), app cached in browser.
3. Close browser and disconnect from Internet.
4. Launch app.  Only phantom symbols appear, not the feature layer symbology.
![online](https://cloud.githubusercontent.com/assets/9742283/5265933/59ab1968-7a14-11e4-991c-2f4fdd31df1f.png)
![offline](https://cloud.githubusercontent.com/assets/9742283/5265938/643357f6-7a14-11e4-946f-fb71340966a3.png)

**Comment by andygup** [comment]
@cy-nwg did this get resolved?

**Comment by cy-nwg** [comment]
This got resolved, but not using the original approach:

In full offline mode, it appears like the feature layer isn't being fully reconstructed appropriately.  I the code to serialize the full layer JSON ($.getJSON(serviceUrl + "?f=json")).  Additionally, for polygons, the opacity was not getting set, so this had to be serialized from the feature layer, and the same was true for the renderer.

localStorage[this._name + "_Symbology"] = JSON.stringify(this._featureLayer.renderer.toJson());
localStorage[this._name + "_Opacity"] = this._featureLayer.opacity;

**Comment by andygup** [comment]
Great info, thanks.

**Comment by andygup** [comment]
@cy-nwg I'm putting together the v2.5 spec. Here's what I have so far for reconstituting a FeatureLayer. If you have anything to add/modify let me know asap?

- FeatureLayer 
 * FeatureLayerDefinition
 * Renderer
 * Optional Properties (which includes opacity, mode, outfields, etc)
- Map.extent 
 * When this is reconstituted you can use getCenter()
- Map.getZoom()
- PhantomLayer Graphics
- Last edit

**Comment by cy-nwg** [comment]
This looks like it covers everything.  If this new spec includes moving the feature layer data to IndexedDb, then it would be nice to also have additional options such as the db name, repository name, etc.

**Comment by andygup** [comment]
In regards to moving the feature layer data to IndexedDB that's #275. Agreed on the DB name, repository name.
