### ISSUE TITLE
FeatureLayer applyEdits or edits-complete

### ISSUE THREAD

**Issue by cy-nwg** [Esri/offline-editor-js#285]
In the appcache-features sample, there is code at the app level which is updating the feature layer when a new feature is added, but the comment says that this should be move to the offline features manager.  I'm wondering if this has been done, or if this type of coding is required at the app level to manage edits?

//Temporary test - this should be added to offlineFeaturesManager
                //Provide a callback of the stringified JSON.
                //Upon restart allows feature layer to show latest edits.
                //Still need to wire this up to phantom symbols somehow.
                //Maybe serialize Phantom graphic layer as well and reconstitute it on restart?
                function updateFeatureLayerJSON(features,id,routes,stopnames){
                    var length = features.length;

                    var f = JSON.parse(localStorage.offlineFeature);
                    var arrLength = f.length;

                    for(var a = 0; a < arrLength; a++){
                        if(f[a].attributes.OBJECTID == id){
                            f[a].attributes.ROUTES = routes;
                            f[a].attributes.STOPNAME = stopnames;
                            var fJson = JSON.stringify(f);
                            if(typeof(Storage) !== "undefined") {
                                localStorage.offlineFeature = fJson;
                                console.log("Done pushing layerDef and features to localStorage.");
                            } else {
                                alert("convertFeatureLayerToJSON: Unable to update Local Storage.");
                            }
                            break;

                        }
                    }
                }

**Comment by andygup** [comment]
@cy-nwg Hi, thanks for the reminder and no this functionality hasn't been integrated into offlineFeatureManager, yet. It's related to #275 and #281, as well as the tweaks you just mentioned in #280. 

I don't have an updated ETA for those enhancements, however it is near the top of my TO-DOs. As we chatted about, I'm still thinking it's best to make these architecture changes all at once rather than piece-meal the functionality a bit at a time and have a kludgy solution. It's going to mean a complete rewrite of editsStore.js along with the new storage capabilities to handle reconstituting feature layers. 

At the end of this, I'm hoping some of the current coding patterns will be simplified.

**Comment by andygup** [comment]
@cy-nwg  For clarification, this functionality in the sample is currently inert -- it writes the data to localStorage but never uses it. The use case was to establish an object reference to the last add, update or delete. 

For example, you can retrieve the last add, update or delete and provide that information to the user AFTER an offline browser restart. If you know of other use cases please let me know.

**Comment by cy-nwg** [comment]
It's been a bit since I looked at this, but I recall the issue was that updates made while offline were not be synced after a browser restart, where the restart came back in online mode.  The workflow was:

- Load app, go offline (no Internet)
- Collect/update data while offline
- Restart browser, offline mode, no problems
- Restart browser, now online, changes are lost

I will retest today and post another update for you.
