### ISSUE TITLE
NetworkError: 404 Not Found - http://esri.github.io/offline-editor-js/samples/jsolib/nls/dojo_ROOT.js

### ISSUE THREAD

**Issue by JorgeUlises** [Esri/offline-editor-js#287]
Hello, I prove the example in demo page http://esri.github.io/offline-editor-js/samples/appcache-features.html and I get the next error message in firebug console:
NetworkError: 404 Not Found - http://esri.github.io/offline-editor-js/samples/jsolib/nls/dojo_ROOT.js
I download the project and put it in web server iis, and get the same error.
Thanks.

**Comment by andygup** [comment]
@JorgeUlises Is there any chance your browser is set to a non-English language? If so, can you temporarily set it to use English and retest?

**Comment by JorgeUlises** [comment]
Yes, this is the problem... So, I change the language in dojo config. 
var dojoConfig = {
        locale: "en-US",
        paths: {
            vendor: locationPath + "/../vendor",
            utils: locationPath  + "/../utils"
        }
    }
Thanks!
