### ISSUE TITLE
Options for OfflineTileEnablerLayer/TileStore

### ISSUE THREAD

**Issue by cy-nwg** [Esri/offline-editor-js#288]
Consider adding options for tile storage:

- Db name & store name:  This allows for better control and management of tile layers.
- No Tile Image: option to show/hide this, or maybe even provide your own image.  When using multiple basemap layers, if one has no tiles, this will display and cover another basemap storage which may have tiles.

**Comment by andygup** [comment]
Thanks, I agree.
