### ISSUE TITLE
Adding secured TileLayer from AGOL - Question 

### ISSUE THREAD

**Issue by Ricardh522** [Esri/offline-editor-js#291]
Hi,

I've been having trouble getting my secured tile layer to load into my map.  The library api docs state that the esri basemaps will work with the o.esri.Tiles.OfflineTileEnablerLayer and they do, should my tile layer from AGOL work in a map that is set to the same spatial reference as the tile layer?  In development I use an app login to get a token and pass it in the url requested for the tile layer.  Will this not work for development using the offline library?  I've since changed to going the user login route because adding my tile layer returns html to the chrome dev tools asking for a user name and password.  I've hid a road block with this approach as well.  It is really important that my application has tiles from my tile layer in AGOL.

The rest of the library has been a breeze to get up and running, I am looking forward to figuring this piece out.

Thanks!

**Comment by andygup** [comment]
@Ricardh522 Can you explain your architecture a little more on how you are attaching the token to the URL? Also, are you seeing any errors that you can pass along here?

OfflineTilesEnablerLayer.js currently only stores information related to the [MapServer URL + level + row + column](https://github.com/Esri/offline-editor-js/blob/master/lib/tiles/OfflineTilesEnablerLayer.js#L117). If you are using POST header attributes then they will be stripped away and not used.

Here's an example of a typical ArcGIS API for JavaScript GET tile requests: http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/13/3168/1310

**Comment by Ricardh522** [comment]
**This is a cut from my map.js**

I have been testing with three different tile layer inputs.  The first is my secure tile layer being used with the offline tile enabler layer with a token appended to the url.  The second is the world imagery service with no token required, the third is my secure tile layer as an ArcGISTiledMapServiceLayer with a token appended to the url.  

The secure ArcGISTiledMapServiceLayer will load and display (with the exception of some errors thrown because it is not in the offline layer format).

The World Imagery Service loads and can be taken offline.  

My secure tiled service in the OfflineTileEnableLayer returns an html user login page to the Chrome response page and does not load.

One difference I noticed between in the url requests is that when I create my ArcGISTiledMapServiceLayer I do not include 'f=pson' at the end of the url.  Both of the other two requests that use the OfflineTileEnablerLayer have 'f=pson' appended to the url by default?.

Below are my tile layers and my map

''' 
tileLayer = new O.esri.Tiles.OfflineTileEnablerLayer(
            "http://tiles.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer?token=" + localStorage['app_tkn'],
            function (evt) {
                console.log("Offline tile lib enabled. App is: " + Offline.state)
            },_isOnline); 

            /*tileLayer = new O.esri.Tiles.OfflineTileEnablerLayer(
            "http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",
            function (evt) {
                console.log("Offline tile lib enabled. App is: " + Offline.state)
            }, _isOnline);*/
            
            /*tileLayer = new ArcGISTiledMapServiceLayer("http://tiles.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer?token=" + localStorage['app_tkn'], {
                
                opacity: 1.0,
                resampling: false,
                
            });*/

            tileLayer.on('error', function (error) {
                console.log(error);
            });

            tileLayer.on('load', function () {
                cred = this.credential;
                map.setZoom(5);
                this.refresh();
            });

            map = BootstrapMap.create("mapDiv", {

                zoom: 1,
                sliderStyle: "small",
                logo: false,
                maxZoom: 8,
                minZoom: 0,
                fadeOnZoom: true,
                force3DTransforms: true,
                extent: new Extent({
                    xmin: 2281519.5,
                    ymin: 14842865.249999993,
                    xmax: 2299097.75,
                    ymax: 14865599.749999993,
                    spatialReference: {
                        wkid: 102709,
                        wkt:"PROJCS['NAD_1983_StatePlane_Nevada_West_FIPS_2703_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',2624666.666666666],PARAMETER['False_Northing',13123333.33333333],PARAMETER['Central_Meridian',-118.5833333333333],PARAMETER['Scale_Factor',0.9999],PARAMETER['Latitude_Of_Origin',34.75],UNIT['Foot_US',0.3048006096012192],AUTHORITY['EPSG',3423]]"
                    }
                }),
                fitExtent: true
            });
            
            map.addLayer(tileLayer);
'''

**Comment by andygup** [comment]
Gotcha. Unfortunately, that URL pattern won't work since the library expects https://someURL/Mapserver/tile/level/row/column. 

Have you tried using the IdentityManager with the regular MapServer url (no token appended)? You didn't mention it so I figured I'd ask.

And, you asked about `f=pjson`. The library does use a `f=pjson` request to verify online/offline status via the [_getTileInfoPrivate()](https://github.com/Esri/offline-editor-js/blob/master/lib/tiles/OfflineTilesEnablerLayer.js#L435) method. It doesn't enforce any other `f=someOption` requests that I can think of.

This may be related to #286.

**Comment by Ricardh522** [comment]
Okay thank you for your clarification.  I do understand the reason why it will not work.  As far as using the Identity Manager goes, I've not been able to implement it *yet.  When following the api documentation I get lost in what is required for the Id Manager to work.  Do I need to do anything with IdManagerBase?    It is something that I need to learn now for sure.

**Comment by andygup** [comment]
Here's a doc to get started with using [secure services](https://developers.arcgis.com/javascript/jshelp/ags_secureservices.html). And there are a [handful of samples](https://developers.arcgis.com/javascript/jssamples/#search/secure) that demonstrate the patterns.

I'll leave this open for investigation for the v2.6 release. The action item will be to confirm that tiled map services do indeed work with HTTPS.

**Comment by Ricardh522** [comment]
I'm wondering whether the offline library will use the identity manager when making the xhr request.  Using esri.request.SetRequestPreCallback I thought I could maybe get the token appended to the request before it gets sent.

**Comment by Ricardh522** [comment]
Hi Andy!  Good news, I was successful in getting the .net proxy to match credentials, secure service, obtain token, and feed tiles into my application using the O.esri.Tiles.OfflineTileEnablerLayer. Another  thing I changed was to use the advanced-src library rather than the advanced-min.  There is another problem though, the tiles won't draw in the map and I cannot see them in the chrome dev tools preview window.  Here is a request that is getting sent with your code.

'''https://tiles.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer/tile/5/36056/35376'''

The response from the proxy is the json of the tile service.

'''{
  "id" : "ad0ff1ad4122ad55",
  "server" : "Apy6bpbM5OoW9DX4",
  "name" : "NAD83_StatePlane_multires",
  "access" : "SECURE",
  "status" : "created",
  "capabilities" : "Map",
  "mapName" : "Map7",
  "description" : "Tile Cache/Package w/3inch aerial at airport with 1 ft aerial backdrop",
  "serviceDescription" : "",
  "initialExtent" : {
    "xmin" : 2280640.5875,
    "ymin" : 1.4841728524999993E7,
    "xmax" : 2299976.6625,
    "ymax" : 1.4866736474999992E7,
    "spatialReference" : {
      "wkid" : 102709,
      "wkt" : null
    }
  },
  "fullExtent" : {
    "xmin" : 2281519.5,
    "ymin" : 1.4842865249999993E7,
    "xmax" : 2299097.75,
    "ymax" : 1.4865599749999993E7,
    "spatialReference" : {
      "wkid" : 102709,
      "wkt" : null
    }
  },
  "spatialReference" : {
    "wkid" : 102709,
    "wkt" : null
  },
  "minScale" : 73728.0,
  "maxScale" : 288.0,
  "units" : "esriFeet",
  "singleFusedMapCache" : true,
  "tileInfo" : {
    "rows" : 256,
    "cols" : 256,
    "dpi" : 96,
    "format" : "PNG24",
    "compressionQuality" : 0,
    "storageFormat" : "esriMapCacheStorageModeCompact",
    "origin" : {
      "x" : -1.5822E7,
      "y" : 3.3315599999999993E7
    },
    "spatialReference" : {
      "wkid" : 102709,
      "wkt" : "PROJCS[\"NAD_1983_StatePlane_Nevada_West_FIPS_2703_Feet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",2624666.666666666],PARAMETER[\"False_Northing\",13123333.33333333],PARAMETER[\"Central_Meridian\",-118.5833333333333],PARAMETER[\"Scale_Factor\",0.9999],PARAMETER[\"Latitude_Of_Origin\",34.75],UNIT[\"Foot_US\",0.3048006096012192],AUTHORITY[\"EPSG\",3423]]"
    },
    "lods" : [ {
      "level" : 0,
      "resolution" : 64.0,
      "scale" : 73728.0
    }, {
      "level" : 1,
      "resolution" : 32.0,
      "scale" : 36864.0
    }, {
      "level" : 2,
      "resolution" : 16.0,
      "scale" : 18432.0
    }, {
      "level" : 3,
      "resolution" : 8.0,
      "scale" : 9216.0
    }, {
      "level" : 4,
      "resolution" : 4.0,
      "scale" : 4608.0
    }, {
      "level" : 5,
      "resolution" : 2.0,
      "scale" : 2304.0
    }, {
      "level" : 6,
      "resolution" : 1.0,
      "scale" : 1152.0
    }, {
      "level" : 7,
      "resolution" : 0.5,
      "scale" : 576.0
    }, {
      "level" : 8,
      "resolution" : 0.25,
      "scale" : 288.0
    } ]
  },
  "supportedImageFormatTypes" : "PNG24",
  "documentInfo" : {
    "title" : "NAD83_StatePlane_multires",
    "author" : "rhughes_AroraGIS",
    "comments" : "",
    "subject" : "Tile Cache/Package w/3inch aerial at airport with 1 ft aerial backdrop",
    "category" : "",
    "keywords" : "cache",
    "credits" : "",
    "Title" : "",
    "Author" : "",
    "Comments" : "",
    "Subject" : "",
    "Category" : "",
    "AntialiasingMode" : "Best",
    "TextAntialiasingMode" : "Force",
    "Keywords" : ""
  },
  "copyrightText" : "",
  "created" : null,
  "modified" : null,
  "layers" : [ {
    "id" : 0,
    "name" : "NAD83_StatePlane_multires_cache",
    "parentLayerId" : -1,
    "defaultVisibility" : true,
    "subLayerIds" : null,
    "minScale" : 0,
    "maxScale" : 0
  } ],
  "tables" : [ ],
  "tileServers" : [ "https://tiles1.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer", "https://tiles2.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer", "https://tiles3.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer", "https://tiles4.arcgis.com/tiles/Apy6bpbM5OoW9DX4/arcgis/rest/services/NAD83_StatePlane_multires/MapServer" ],
  "maxExportTilesCount" : 100000,
  "exportTilesAllowed" : true,
  "currentVersion" : 10.3,
  "type" : "MapServer"
}'''

*** The problem now is that the tiles are not empty when they are brought into the browser***

![tilesempty](https://cloud.githubusercontent.com/assets/5625223/6509236/f99df8fe-c32b-11e4-8f7a-fef7110dbf22.PNG)

**Comment by andygup** [comment]
In theory either identity manager or SetRequestPreCallback will work with the offline library. If you have a chance to test it please post the results.

**Comment by andygup** [comment]
Woops, my browser didn't load your previous comment. Now I see your comment on the JSON response. Do you have Fiddler, Charles or some other debugging proxy app you can run against this to see what's going on behind the scenes?

**Comment by Ricardh522** [comment]
I've been running with Fiddler and see that each tile is returning with an .html user login page.  If I enter my username and password I see the tile.  I've required the Identity Manager and the Identity Manager Base in my map code, but I am not passing it any server information or credentials right now.  Previously I experimented with App Login to generate a token,  followed by testing a user login with redirect to oauth-callback.html to parse a token.  In both separate cases I registered the token with the esriId.  I would inspect the esriId and view the serverInfos, credentials, and oAuthInfo that I registered manually.  All of it seemed to be in order but I did not have success with the TileEnablerLayer(url, callback, _isonline).  The url requests were sent without a token and failed to access the tiledmapservice in agol.  

I've spent lots of time working with various arrangements of the esriId, but I have not been able to determine which way is the correct way to use it.  Without having a definitive method to test against my results are not conclusive.  

Security of the application is an issue, so in the end having all of the authorization information in a proxy makes the most sense to me and it easy to manage.

This does add the proxy as a variable with the added benefit of logging errors and successes.  For whatever reason, my user login information is just not getting through to retrieve the individual tiles.  This is even after the map service has responded with the json service definition.  The spatial component of the service is returned so my map can pan and zoom while having the scalebar adjust accordingly.  Also, through a GET request, new tiles are retrieved when the map refreshes (only there is no data).  

Should this be a GET request for the individual tiles after the proxy has authenticated and accessed the tiledMapService?  I am thinking that there is an issue with the type of, or formatting of the request being sent for each tile from the offline library.  

I'm fully invested in this solution so I will be happy to test any setup you have in mind.

Thanks,

**Comment by andygup** [comment]
It doesn't look like there are any quick fixes to this. I can confirm the architecture does not currently inherit or persist the tokens. 

I won't be able to get to this until v2.6 which is tentatively scheduled for April. There are also several other HTTPS fixes pending for the library. If you want to tackle trying to implement a temporary fix I can tell you which public and private methods will need to make tokenized requests?

------

I can see here that it's clearly failing when it tries to get the tile layer info. [_getTileInfoPrivate](https://github.com/Esri/offline-editor-js/blob/master/lib/tiles/OfflineTilesEnablerLayer.js#L433) throws the following error:

![image](https://cloud.githubusercontent.com/assets/510440/6531047/1ae14eea-c3f3-11e4-9943-699d698a3c9c.png)

**Comment by Ricardh522** [comment]
Hi Andy, so I explicetly appended token and client_ I'd to functions in that required a url.  This does now draw my tiles while online!  The only other thing that requires some time is to get the offline tiles to operate according to spec.  Maybe I'll be ale to show a working offline app at the dev summit.  I am flying out there on Monday.  Your IndexDb session is on my planner.  Richard

**Comment by andygup** [comment]
Awesome! See you next week.
