### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by saif984** [Esri/offline-editor-js#293]
i working on create Offline app that store tile from Local arcGIS server.

when it tries to cache tile, i got the following Error:
XMLHttpRequest cannot load {GIS Service on my network (not online)}. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '{ApplicationServer}' is therefore not allowed access.

Since loading Map without using downloading tiles works fine.

is there any configuration must to do on ArcGIS Server?

**Comment by andygup** [comment]
@saif984, I have a few questions:
* Are you using one of the sample applications? If so, let let me know which one?
* When you say 'Local ArcGIS Server' do you mean it's running on the same machine that you are doing software development on, or it's simply in the same building?
* If ArcGIS Server is in the same building (and not on your development machine) is the web server configured for CORS? If it isn't are you setting the proxyPath property for `layer.offline.proxyPath`? 
* And, can you post a copy of the header information from a successful request to load a tile along with an unsuccessful attempt?

Example HTTP request header information (from Chrome developer tools console):

**Request** URL:http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/13/3045/4074
Request Method:GET
Status Code:200 OK

**Response Headers**
Access-Control-Allow-Origin:*
Cache-Control:max-age=86400
Connection:keep-alive
Content-Length:15404
Content-Type:image/jpeg
Date:Mon, 23 Mar 2015 14:38:58 GMT
ETag:"qkpm1r67ffs"
Server:Apache

**Request Headers**
view source
Accept:image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:server.arcgisonline.com
Pragma:no-cache
Referer:http://<your_web_server_name>/offline-editor-js/samples/draw-pointlinepoly-offline.html

**Comment by andygup** [comment]
@saif984 were you able to get the app working?

**Comment by andygup** [comment]
I'm going to close this for now.
