### ISSUE TITLE
Support both ADD and UPDATE attachment

### ISSUE THREAD

**Issue by andygup** [Esri/offline-editor-js#305]
Need to make a distinction between an ADD and UPDATE. 

Use cases:
- ADD new attachment
- UPDATE new attachment > convert to an ADD operation
- UPDATE existing attachment (uses existing ObjectId and AttachmentId)

**Comment by andygup** [comment]
Use the method signature `updateAttachment: function(/*Number*/ objectId, /*Number*/ attachmentId, formNode, callback, errback)`. Confirmed that this exists in the JSAPI it's just not currently documented.

**Comment by hnasr** [comment]
Hey Andy,

Allow me first to express my deep great appreciation this great library! Great work, 

I have few questions, 

The OfflineFeatureManager handles the editing session between the client side and the feature service.  When in offline mode, the manager queues in the edits locally in memory (correct me if i'm wrong), and pushes them back online once a connection is available. This is possible when the browser is not refreshed, that means I still have my instances of the manager and other objects. 

You said it is possible to do a full-offline scenario, where by I can safely restart the browser or if I accidentally closed my browser I could still get my offline edits, by using the data store object in the offlinefeaturemanager. Question is, when I set a data store object in the offlinefeaturemanager constructor, where does this get stored? browser cookies? we know that we can't write to the local drive if we are in the browser using Javascript. Plus how does the browser know how to retrieve the datastore back after a browser restart? From where the function getFeatureLayerJSONDataStore() retrieves back my session? does it keep track of my particular browser session internally? 
 
I would appreciate if you could expand on this topic.

Thank you
Hussein Nasser

**Comment by andygup** [comment]
@hnasr Thanks for the feedback and questions. This question probably should have been opened as a new issue. At some point I need to add an FAQ to help with these types of questions, so I'll open an issue for that.

**Note:** working in full offline browser mode is very different from online/partial-offline and requires having good knowledge of using the browser's [Cache Manifest](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache), and of web application/DOM life-cycle patterns and practices. It may also require advanced debugging skills to help troubleshoot offline life-cycle issues.

>>when I set a data store object in the offlinefeaturemanager constructor, where does this get stored?

Feature edits are stored in an [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) database. Attachments and map tile data are also stored in separate IndexedDB databases. 

**Note:** The maximum amount of IndexedDB storage varies from device to device. Generally speaking, you can store up to a total of 50MB - 100MB (or greater). It depends on numerous factors related to the browser including how many browser-based databases are being used, how much total memory the browser has consumed, how large the browser cache has grown, how many other tabs may be open, and how much memory other applications are already consuming.

If someone clears the browser cache they may also end up clearing any browser database data stored in IndexedDB.

>>Plus how does the browser know how to retrieve the datastore back after a browser restart?

You have to programmatically retrieve the `dataStore` after a browser restart. Refer to the API "How to use" documentation. Go to [API docs home page](http://esri.github.io/offline-editor-js/demo/api-doc.html) > Offline Features - [How to use](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseeditlibrary.md).

There are also several sample applications that demonstrate working with the library in full offline scenarios:
* Working with features and tiles - [appcache-features.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html)
* Working with tiles only - [appcache-tiles.appcache](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-tiles.html)
