### ISSUE TITLE
npm v2.4

### ISSUE THREAD

**Issue by jaymcneil** [Esri/offline-editor-js#314]
Hey Andy,

This is probably just an issue with me; I'm not an expert with node.  I keep running into an issue when I try to build the _min and _src libraries in to \dist.  (ex.  npm install).  I was getting this error with v2.5 and then I upgrade to 2.7.5 and still running into the same problem.  Sorry for posting the question here...I searched stackoverflow and the web but had no luck.  

Any ideas.

8 error argv "node" "/usr/local/bin/npm" "install"
9 error node v0.12.2
10 error npm  v2.7.5
11 error Invalid version: “2.4”

Jay

**Comment by andygup** [comment]
@jaymcneil just a hunch. In the root/package.json file try renaming the version property from "2.4" to "2.4.0".

**Comment by andygup** [comment]
@jaymcneil any luck?

**Comment by jaymcneil** [comment]
@andygup yes that worked...sorry for the delay...got swamped.
