### ISSUE TITLE
Full Offline Add New Feature Update Attributes Issue

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#339]
I’m seeing a situation where when I add a feature while fully offline, and then update the attributes of it, while still offline, an error is occurring.  It appears the replay of edits when back online, the library is sending it as an update, although that won’t work since it’s never been added.

**Comment by andygup** [comment]
It did look at this over the weekend and sure enough it looks like the logic is missing to handle that use case. Deletes are handled correctly but add > update isn't. 

I'll get a fix out to your this afternoon or first thing tomorrow.

**Comment by webmapsolutions** [comment]
I'm still seeing issues here. See the video walking through what I am seeing:

http://webmapsolutions.com/demos/OfflineError/OfflineError.html

**Comment by andygup** [comment]
Interesting, it's hard to say without seeing the code that runs after `applyEdits()` inside your main application. I'm fairly certain the `onedits-enqueued` error is not coming from this library.

Do you have a public version of the app I can spin up for a quick run?

**Comment by webmapsolutions** [comment]
One other addition here Andy. Here is the workflow:
1. Take application fully offline 
2. Add new feature
3. Update attributes
4. Shut down browser
5. Bring browser back up
6. New feature is not rendered (visible) on map
7. Go back fully online
8. New feature is pushed to ArcGIS feature service successfully

So all works well apart from point 6 above. Let me know if this makes sense.

Thanks

**Comment by andygup** [comment]
I bet with just a little tweaking you'll have it. Try something like this subtle variation of the workflow:
5. Bring browser back up.
6a. If online then sync all edits first 
6b. If offline then recycle offline workflow. It's important to make sure that when using a `featureLayerCollection` to build the `FeatureLayer` that it includes all the latest edits. This is an easy step to miss.
7. After sync completes then reconstitute feature layer like normal using the feature service end point.
