### ISSUE TITLE
FeatureLayer events not triggering while offline

### ISSUE THREAD

**Issue by bsquires16** [Esri/offline-editor-js#341]
I created the featureLayer from a featureCollection in order to limit the amount of features rendered. This approach worked well. When I download and disconnect everything is stored properly and displays correctly. The only issue is when I close the browser, open it again, and navigate to the page. The page displays correctly and retrieves all tiles. I’m having an issue with the featureLayer, I can see that the features are stored. The featureLayer events are not being triggered (update, update-end). I created listeners for both these events but they aren’t being triggered when it’s offline. So I can’t call the initOffLineFeaturesMgr function. Any suggestions will be greatly appreciated.

**Comment by andygup** [comment]
@bsquires16 first, make sure you are on v2.8.1. It includes a bunch of enhancements specifically your workflow.

The [How-to](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseeditlibrary.md) doc goes into some detail on the patterns to use.

Also, take a look at the latest version of [appcache-features.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html) beginning at the `update-end` listener at [Line 306](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html#L306).

If you are following a similar pattern and it's still not working, can you post some psuedo-code for me to look at?

**Comment by bsquires16** [comment]
Hi Andy,

Thanks for the response. I went through the documentation and made a few tweaks and everything works well on my desktop. Now I have to figure out a few things on the tablet.

**Comment by andygup** [comment]
Awesome. Let me know if you have any suggestions (e.g. documentation, samples, etc) on improvements based on your experience.

**Comment by andygup** [comment]
@bsquires16 any luck on the tablet?

**Comment by bsquires16** [comment]
Hi Andy,

Sorry for the late reply, I was on vacation. I was able find out why it wouldn't work on the tablet. The "verifyOnline" function was failing because the req.status returned 0 while the req.responseText was actually a value with a correct response. So I had to include (req.status === 0 && req.responseText !== "") in order for it proceed as expected.

**Comment by andygup** [comment]
@bsquires16 No worries. Interesting. What OS version and browser are you using? Just in case anyone else runs into the same issue.
