### ISSUE TITLE
Support Dojo's 'lite' selector engine?

### ISSUE THREAD

**Issue by saclarky** [Esri/offline-editor-js#349]
I broke 'offline-tiles-advanced-src.js' at ~line 811 (image = query("img[src="+tileid+"]")[0];) by using Dojo's lite selector engine. It took me a while to figure this out, but changing the selector engine to 'acme' in my dojoConfig fixed the issue.

I haven't looked to see if the query could be reformatted to be supported by lite, but wanted to bring it up. Thanks!

**Comment by andygup** [comment]
@saclarky Good catch. Nope, no plans to support it specifically. The goal is for the libraries to be as framework agnostic as possible. I know there is occasional use of dojo shorthand where it provided simplification, such as the `query` that you pointed out. I'm also (very) aware that sometimes that pattern of simplification can introduce hidden dependencies. 

So, if there are generic, plain old JavaScript work-arounds that work on the latest versions of Chrome, Safari and Firefox then I'm open to considering those.
