### ISSUE TITLE
Symbology Edits

### ISSUE THREAD

**Issue by countrytoast** [Esri/offline-editor-js#350]
In my service, symbology is applied to each polygon depending on the string value in the polygon.

In the modal pop up, the value of the symbology field, which is usually a string, has been turned into a number. Is there any way to change it so that it comes up as the string it should be?

Also are subtypes/domains supported? could I add a dropdown list to a modal popup?

Thanks!

**Comment by andygup** [comment]
>> Is there any way to change it [modal popup] so that it comes up as the string it should be?

The modal popup widget included in the `/samples` directory is just a static, customizable framework that accepts whatever values are passed into it. Check the value that is being passed into the particular element by your application.

>> Also are subtypes/domains supported?

No, they aren't supported by the OfflineFeaturesManager.js library. If you need support for subtypes and domains then I recommend looking at our ArcGIS Runtime SDKs for example: [Editing an ArcGISFeatureLayer - ArcGIS Runtime SDK for Android](https://developers.arcgis.com/android/guide/edit-an-arcgisfeaturelayer.htm)

>> could I add a dropdown list to a modal popup?

Absolutely, feel free to modify the widget as needed to meet your requirements. All the code is available under [`/samples/widgets/modal`](https://github.com/Esri/offline-editor-js/tree/master/samples/widgets/modal).
