### ISSUE TITLE
About Loading Tiles for Offline Map

### ISSUE THREAD

**Issue by Elhazard** [Esri/offline-editor-js#351]
When I tried to save Tiles for offline map, sometimes it can load normally, sometimes it is really slow, sometimes loading progress is still at 0% for a long time

I wonder are there any factors rather than internet speed when downloading tiles for offline map?

**Comment by andygup** [comment]
@Elhazard Did you check the browser's developer console under the Network tab? The most likely candidate is network speed. You can also trying limiting the extent and level of tiles that are being retrieved.

**Comment by andygup** [comment]
@Elhazard any luck?

**Comment by Elhazard** [comment]
Sorry for late response. I already told my supervisor who asked me this question and she already understood what you explained.

Thanks

**Comment by andygup** [comment]
Gotcha. I'll close for this now then.
