### ISSUE TITLE
Cannot read property 'deleteAllTiles'

### ISSUE THREAD

**Issue by pwild** [Esri/offline-editor-js#354]
Offline Tiles - Advanced advanced error from my on premise server and custom tile cache with ssl :

"Uncaught TypeError: Cannot read property 'deleteAllTiles' of undefineddownloadTiles @ (index):241
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError"

1.1mb being transferred

Kinda stumped. Any insight appreciated.

**Comment by andygup** [comment]
Can you confirm if you are using OfflineTilesEnabler or OfflineTilesEnablerLayer? 

And, under what circumstances is this error occurring? For example, is it happening when the internet is restored, or does it happen after an offline restart?

If you are using OfflineTilesEnabler, have you looked at the [appcache-tiles.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-tiles.html) sample for comparison?

I'll also make some updates to the How To Use Tiles doc. I see there is some info missing.

**Comment by pwild** [comment]
Andy, 
I am using OfflineTileEnablerLayer. The map loads without errors, console reports: Offline tile lib enabled. App is: up.

When I click on '1.Download Tiles'  console reports the error.

I see in the API/How to use :
O.esri.Tiles.OfflineTilesEnablerLayer

However in the Get Started code I see:
O.esri.Tiles.OfflineTileEnablerLayer

When I place the 's' after tiles I receive an error.

Thanks for the quick response!
PW

**Comment by andygup** [comment]
Oops. Good catch, I thought that was fixed a long time ago. I'll be pushing an update shortly.

**Comment by andygup** [comment]
Just to clarify. For now I'm just going to fix the documentation. I'll leave the typo in the library name alone for the moment so as to avoid a breaking change to offlineTileEnablerLayer.
