### ISSUE TITLE
Edits Database Cleanup

### ISSUE THREAD

**Issue by cy-nwg** [Esri/offline-editor-js#361]
Andy, when users are offline for extending periods of time, there may be cases where a large number of edits are saved in the offline database.  When users go back online, wondering if you could add an enhancement to cleanup the database immediately, rather than at the end of the process.  Seems like it would greatly increase the robustness of the library.

**Comment by andygup** [comment]
Agreed, good catch. I chatted with Matt a little about the implementation details. I'll schedule some time to knock this out.
