### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by albertogonper** [Esri/offline-editor-js#372]
Hello,

Can you publish this to npm? So I can include it on my project as a dependency to keep it up to date.

I think that this also would be useful for other developers.

Excelent work!

Thanks

**Comment by andygup** [comment]
Absolutely! Thanks for the reminder it's been on my TO-DO list for a while.

**Comment by andygup** [comment]
@albertogonper just a note. The npm tie-in is going to be part of an upcoming minor release of this repo that will automate a bunch of manual github/gh-pages/npm steps.

**Comment by andygup** [comment]
The npm package for this repo is now available at: https://www.npmjs.com/package/esri-offline-maps

**Comment by albertogonper** [comment]
Excellent! Thank you so much!
