### ISSUE TITLE
TilesStore does not always load.

### ISSUE THREAD

**Issue by YusufQ** [Esri/offline-editor-js#373]
An exception comes up with offline-tpk-min.js. O.Esri.Tiles.TilesStore does not load.

"Uncaught TypeError: Cannot set property 'TilesStore' of undefined"

![issue](https://cloud.githubusercontent.com/assets/10925002/8850704/dda584d8-3152-11e5-8ce1-fa7dfc64cb01.jpg)

**Comment by andygup** [comment]
@YusufQ I'm unable to duplicate so my first recommendation is to use the non-minified [source code](https://github.com/Esri/offline-editor-js/blob/master/dist/offline-tpk-src.js) file that in the `dist` directory. 

Once you've done that please re-run and send the offending code block.

**Comment by YusufQ** [comment]
@andygup I replaced the source code with a non-minified js file, looks like the problem is solved. 
I will send the offending code block if the problem appears again. 

Many Thanks.

**Comment by YusufQ** [comment]
@andygup The problem is not solved. It is still sometimes do not load fine, sometimes but not always. 

As you can see the offending code block has error that esri Object is available but Tiles is not available!


![issue](https://cloud.githubusercontent.com/assets/10925002/8902198/b8782802-3457-11e5-9531-43f9e93e42d1.png)
