### ISSUE TITLE
Problem with the offline tile layer enabler and the new client side geometry engine (beta).

### ISSUE THREAD

**Issue by bjvanmet** [Esri/offline-editor-js#374]
Hi there.

I have an issue where I cannot use the geometry engine in ArcGIS JS api v3.13 to make a buffer zone if an offline tile layer exists. The offline enabled layer doesn't even have to be loaded into the map. Just the presence of an offline layer object will cause geometry engine errors (at least with buffer zones). There must be something in the way it extends the tile layer class. The error I get is cryptic to say the least since it comes from obfuscated code but I feel like the client side geometry engine is something that would compliment this offline editing and tile caching quite nicely.

The error pretty much says "Type error: h is undefined" coming from geometryengine.js, which is meaningless when looking at the obfuscated JS code, but to someone who had access to the geometry engine source, it could be debugged.

Feel free to contact me directly via email if you need any additional details or cannot recreate the issue: bryan@amalgamonline.com

Thank you much,

-Bryan

**Comment by andygup** [comment]
Bryan, can you provide a code sample, gist or paste a code snippet here in this github issue?

**Comment by bjvanmet** [comment]
Hi Andy.

Not sure exactly where to start or what would be helpful in terms of what to code to share so you can get a better idea as to what's going wrong. I guess I'll just give more detail.
I'm using the standard build of the ArcGIS JavaScript API rather than the one provided in the CDN, but I did make sure to grab the geometry engine components as well.

This is where I create the offline object, and it does work like it's supposed to:
	midlandImageryOffline = new O.esri.Tiles.OfflineTileEnablerLayer("http://tiles.arcgis.com/tiles/blE8NdGZSd9Sfngv/arcgis/rest/services/midImagery/MapServer", function(){
		console.log('offline imagery object added to DOM');// the API throws errors if you don't specify some sort of callback function...
	}, true);
	midlandImageryOffline.id = "midlandImageryOffline";
	midlandImageryOffline.offline.proxyPath = "http://www.fetchgis.com/proxy/proxy.ashx";

I'm not sure why this would break the geometry engine though. I'd be happy to email you my Dev URL, but I don't feel comfortable sharing it here where it is public.

Here is a sandbox for the geometry engine buffer I use:
https://developers.arcgis.com/javascript/jssamples/ge_geodesic_buffers.html

Hopefully any of this helps.

Thanks,

-Bryan

**Comment by andygup** [comment]
Gotcha. Email the URL to agup at esri dot com and I'll take a look.
