### ISSUE TITLE
TilesStore does not always load.

### ISSUE THREAD

**Issue by YusufQ** [Esri/offline-editor-js#375]
@andygup The problem is not solved. It is still sometimes do not load fine, sometimes but not always.

As you can see the offending code block has error that esri Object is available but Tiles is not available!

![issue](https://cloud.githubusercontent.com/assets/10925002/8902672/306529c0-345b-11e5-9c8b-023060f81733.png)

**Comment by andygup** [comment]
@YusufQ I have some questions to try and narrow this down:

* Do you have this problem when you run the `tpk-layer.html` sample multiple times?
* Please share/paste a copy of the block of your custom code that is executing when the error occurs. Even better would be if you have an online sample or full source code that reproduces the issue. 
* Are you trying to access TilesStore directly in your custom code?
* Also include a copy of the console log dump. I need to know if there were any errors or warnings.

**Comment by andygup** [comment]
Any luck?

**Comment by YusufQ** [comment]
@andygup  Yes! 

My Map was not contain any tile layer, I just have a tpk and Feature layers, some times it was give me that error .. 

after I read your question : Are you trying to access TilesStore directly in your custom code?

I tried to access the TileStore directly, so the error disappear!! 

Old : O.esri.Tiles.TileStore()
New : O.esri.TileStore()

I changed the function name. I did not understand what exactly happened, but it's works fine. 

Many thanks for your help. 
- Yusuf Ali

**Comment by andygup** [comment]
>> I changed the function name. I did not understand what exactly happened, but it's works fine.

@YusufQ Glad the intermittent error has gone away. However, I'd really like to understand more about what is happening as it may help others who might experience the same issue. Especially if this is a bug I would love to be able to replicate it. The library is designed that in the majority of cases you should never have to access the database directly.

Please take a moment to provide the following information:
* Do you also experience this problem when you run the `tpk-layer.html` sample, or does it only occur in your custom-built application?
* Provide a copy of the block of your custom code that is executing when the error occurs. Even better would be if you have an online sample or full source code that reproduces the issue. 
* Also include a copy of the console log dump. It would be very helpful to see if there are any console errors or warnings.
* What device manufacturer, operating system version, browser version?

This additional information would be very helpful!

**Comment by andygup** [comment]
Closing this for now pending further information.
