### ISSUE TITLE
Chrome Issue on iOS

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#382]
We have been testing the following two links in Chrome (current version) on various devices:

http://webmapsolutions.com/umv/viewer/
http://webmapsolutions.com/demo/disconnectedJSDocs/samples/

On an iPad 2, 3, iPhone 4 both links load without a problem. On an iPhone 6 and iPad Mini (first version) neither load correctly. My suspicion is it is an appcache issue. The failed pages for each of these links respectively can be see here. In each case the basemaps are not loading:

http://webmapsolutions.com/bugs/umv.png
http://webmapsolutions.com/bugs/samples.png

**Comment by andygup** [comment]
Matt, can you paste in a copy of your console.log? I want to be certain of the errors you are seeing so I can compare. You should be able to use remote debugging +  USB cord to capture the errors on Android/Chrome and iOS/Safari.

**Comment by andygup** [comment]
Matt, I have a few application cache debugging suggestion to save you a ton of headaches since Safari 8 runs like a slightly modified clone of IE6. 

You find additional information for listening to application cache events [here on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache).

You'll have to manually delete the application cache by digging down into Safari's filesystem directory as shown [here](http://stackoverflow.com/questions/5615266/how-do-you-clear-the-offline-cache-for-web-apps-in-safari). After deleting the application cache, then close and restart the browser.

Lastly, Safari does not write any application cache messages to the console on it's own. So, be sure to add the following code in the `<head>` section and then you'll be able to see what's going on with the application cache loader status and it will print out any errors.

```js
    <script>
        // DO NOT DELETE!
        // Listen for application cache update events
        // We want to place this as early in the application life-cycle as possible!
        window.addEventListener('load', function(evt) {

            window.applicationCache.addEventListener('updateready', function(evt) {
                if (window.applicationCache.status == window.applicationCache.UPDATEREADY) {
                    // Browser downloaded a new app cache.
                    if (confirm('A new version of this cache is available.')) {
                        window.location.reload();
                        console.log("App cache reloaded");
                    }
                } else {
                    // Manifest didn't changed. Nothing new to server.
                    console.log("App cache no change");
                }
            }, false);

        }, false);

        function logEvent(event) {
            console.log("Checking for Application Cache Event: " + event.type);
        }

        window.applicationCache.addEventListener('checking',logEvent,false);
        window.applicationCache.addEventListener('noupdate',logEvent,false);
        window.applicationCache.addEventListener('downloading',logEvent,false);
        window.applicationCache.addEventListener('cached',logEvent,false);
        window.applicationCache.addEventListener('updateready',logEvent,false);
        window.applicationCache.addEventListener('obsolete',logEvent,false);

        // If you need to catch AppCache errors as early as possible to troubleshoot errors.
        // You should delete this for production use.
        window.applicationCache.addEventListener("error",function(err){
            console.log("ApplicationCache listener: " + err.toString());
            if (confirm('There was a problem setting this app up for offline. Reload?')) {
                window.location.reload();
                console.log("App cache reloaded");
            }
        },false)
    </script>

```

**Comment by andygup** [comment]
Hey Matt, I'm going to close this issue. If the issue comes back up, please feel free to reopen.

**Comment by webmapsolutions** [comment]
Willdo Andy. I still see it, but will try to provide information.

On 13 August 2015 at 12:05, Andy <notifications@github.com> wrote:

> Hey Matt, I'm going to close this issue. If the issue comes back up,
> please feel free to reopen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/382#issuecomment-130782770>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>
