### ISSUE TITLE
getMinMaxLOD calculation

### ISSUE THREAD

**Issue by pstevlingson** [Esri/offline-editor-js#386]
Please look at the getMinMaxLOD calculation in offline-tiles-advanced-src.js.   I believe that line 241 should be a subtract not an add.

var min = map.getLevel() + minZoomAdjust;

Great library by the way.  It is turning out to be very useful.

**Comment by andygup** [comment]
Good catch! 

This will need to be updated in two places: `offlineTilesEnabler.js` line [300](https://github.com/Esri/offline-editor-js/blob/master/lib/tiles/offlineTilesEnabler.js#L300) and `offlineTilesEnablerLayer.js` line [238](https://github.com/Esri/offline-editor-js/blob/master/lib/tiles/OfflineTilesEnablerLayer.js#L238).

Also adding a note here to recheck that the doc reminds folks to use this in conjunction with `getMinZoom()` and `getMaxZoom()`.
