### ISSUE TITLE
In offlineFeatureManager, wait for pushPhantomGraphic callback before setting attributes and styles

### ISSUE THREAD

**Issue by robkspeer** [Esri/offline-editor-js#390]
When extending a layer, on the private _pushValidated(edit)FeaturetoDB methods, it's possible to try to try to set the phantom graphic attribute and style before the _editStore.pushPhantomGraphic callback is complete.  This would result in a "cannot set attribute of null" error and the method's deferred will not resolve.

These two lines should be moved up within the pushPhantomGraphic callback function so they are only run with a successful callback:
`                                        domAttr.set(phantomUpdate.getNode(), "stroke-dasharray", "5,2");
                                        domStyle.set(phantomUpdate.getNode(), "pointer-events", "none");`

**Comment by andygup** [comment]
Did you want to tackle this one plus #386?

**Comment by robkspeer** [comment]
Sure thing, I'm on it.
