### ISSUE TITLE
Multiple Features and indexDB Storage

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#391]
I've been testing loading multiple feature layers into a viewer using the library. When I look in indexDB I'm only seeing one feature layer stored. And yet when I go fully offline all features are being returned. Just wondering if I am missing something?

**Comment by andygup** [comment]
There aren't any errors in the console.log? 

The `id` of any edit is converted into a universally unique identifier (UUID) using the following [formula](https://github.com/Esri/offline-editor-js/blob/master/lib/edit/editsStore.js#L46):

` id: layerUrl + "/" + graphic.attributes[this.objectId]`

There are a number of possibilities why edits to a particular layer won't show up.
* the layer never got initialized for offline use. 
* the layer was initialized correctly, however it's set to online-mode and edits are simply passing on thru to the feature service.
* An error is occurring that's preventing the offline edit operation from completing and correctly writing the meta data to the database.

You can also check in the database's feature collection object. For example, if you have set `offlineFeaturesManager.ENABLE_FEATURECOLLECTION = true;` then you'll be able to see all feature layers that have been initialized by looking at the entry in the database for `id = feature-collection-object-1001`:

![image](https://cloud.githubusercontent.com/assets/510440/9184989/eded707c-3f75-11e5-8456-d183292290da.png)

More details are available in the [How to use](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseeditlibrary.md) doc.

**Comment by andygup** [comment]
Oh, sorry just re-read your question. I'm assuming you are using Chrome? The results you see in the Chrome console are very, very flaky. It doesn't update the display table dynamically. You have to close the dev console and reopen to refresh the info.

**Comment by webmapsolutions** [comment]
I'll close this for now Andy. After looking at the code for some time today, my suspicion is this is an issue with our implementation.
