### ISSUE TITLE
Tile Package Errors with images to show

### ISSUE THREAD

**Issue by Ricardh522** [Esri/offline-editor-js#395]
![tileinfo](https://cloud.githubusercontent.com/assets/5625223/9212779/f435a802-4059-11e5-9f5a-2283e57f208d.PNG)
![resofundefined](https://cloud.githubusercontent.com/assets/5625223/9212781/f63bd5c2-4059-11e5-8626-525c09613bb7.PNG)

I've been asked to enhance our mobile html5 application with the tile package feature for viewing offline.  The errors show after the callback(tileInfo).  Both tileInfo and the lods assigned to them on the previous line are valid as far as I can tell.  

Are there lod requirements for the tile package when it is viewed by itself?  This is a small tile package with only features, 6 lods, state plane projection in feet.

What i've done is use the sample tile package app and add the code into a widget.  I set the map extent and projection to be the same as the information returned from the server in the GET request.

**Comment by andygup** [comment]
@Ricardh522 Here's the [How to](https://github.com/Esri/offline-editor-js/blob/master/doc/howtousetpklibrary.md) doc. All the API and How To's for this repo can be found [here](http://esri.github.io/offline-editor-js/demo/api-doc.html).

If you are using a tiled base map with a .TPK (tile package) the TPKs Levels of Detail (LODs) **must match** the tiled map services LODs exactly. In other words, State Plane tile packages will have to be used on top of a State Plane base map, etc.

The basemap (base tiled layer) defines the LODs that the map can display. Any other operational tiled layers on the map will not display if they don’t match the basemap’s LODs. Esri.Map doesn’t apply a union to LODs of all tiled layers on the map.

**Comment by andygup** [comment]
@Ricardh522 any luck?

**Comment by Ricardh522** [comment]
Hey Andy,  No luck with the tile packages.  It was a short lived attempt then I jumped back onto my track with the multiple features from the map service and downloading tiled imagery.  As far as I could tell though my empty map and the tile package were in the same projection.  What is the required MIME type for using the .zip file as a tile package?

**Comment by andygup** [comment]
The MIME type for IIS should be `application/zip`. 

Can you send me a URL to the app and a link to the TPK? If you don't want it public you can email it to me agup at esri.

I'd really like to know if there is something in your TPK that is unique or if there is a bug in the TPKLayer library.
