### ISSUE TITLE
potential bug in offline-edit-src.js at line 1336 editStore.init

### ISSUE THREAD

**Issue by pstevlingson** [Esri/offline-editor-js#397]
I thought I would start from the bottom up with the problem description, so I would point out the exact place where I think the bug is, but my explanation may be a bit convoluted.  

Using offline-editor-js - v2.13.0 - 2015-08-10.

Line 1336 in offline-edit-src.js executes editStore.init and passes a callback.  The callback resolves a deferred closure variable called "deferred".   However, the target function this.init at line 3205 never executes the callback, so the deferred is never resolved.    The resolved deferred is needed to execute other code that loads features from the database into feature layers.

getFeatureCollections at line 1269 is calling initializeDB and assigning a ".then" which is waiting for the deferred to be resolved by the call back passed to editStore.init.   SInce it never resolves the deferred variable,  the this._editStore._getFeatureCollections function never gets executed and my custom call back is also not executed.

I found this because the anonymous call back that I pass to offlineFeaturesManager.getFeatureCollections is not being executed.  

I'm attempting a browser restart using "Approach 2" as described in the https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseeditlibrary.md.   

I can see both tile and feature databases in chrome developer tools.   The code is able to successfully open the feature database at line 3208 in the this.init function.

    offlineFeaturesManager.getFeatureCollections(function(success, collection) {
      if(success) {
        for(var x=0;x<collection.featureCollections.length;x++) {
          var newFeatureLayer = new FeatureLayer(collection.featureCollections[x].featureLayerCollection,{
                            mode: FeatureLayer.MODE_SNAPSHOT,
                            outFields: ["*"]
                          });

          offlineFeaturesManager.extend(newFeatureLayer,function(result, error) {
            if(result) {
              console.log("Layer has been successfully rebuilt while offline!");
            }
          });

          _layers.push(newFeatureLayer);
        }
      }

**Comment by pstevlingson** [comment]
My first explanation is not exactly correctly.   It appears that the call back is supposed to happen via the request that is passed back by the indexedDB.open function.   

I'm investigating further.

**Comment by pstevlingson** [comment]
It appears that the "request" functions in this.init at line 3205 , onerror, onupgradeneeded and onsuccess are not getting called.  I put break points in them and the code never entered those functions.  I'm checking to see if there is another handler that it might be trying to call.

**Comment by pstevlingson** [comment]
When I run the application in IE11, the onsuccess handler at line 3229 is being executed.  When I run it in the latest version of chrome it is not.   

I am investigating further.

**Comment by andygup** [comment]
@pstevlingson this library doesn't support IE in any version due to a wide variety of limitations. As per the README, it only supports the latest versions of Chrome, Safari and Firefox.

Can you post the console.log dump and the offending code block from your application? Even better would be a public repo I can take a look at.

The most common issues related to the editStore not initializing correctly has to do with your application life-cycle.

**Comment by pstevlingson** [comment]
The block of code is the one below.   Its not executing the call back.   I'm working on getting the console log now.

offlineFeaturesManager.getFeatureCollections(function(success, collection) {
  if(success) {
    for(var x=0;x<collection.featureCollections.length;x++) {
      var newFeatureLayer = new FeatureLayer(collection.featureCollections[x].featureLayerCollection,{
                        mode: FeatureLayer.MODE_SNAPSHOT,
                        outFields: ["*"]
                      });

      offlineFeaturesManager.extend(newFeatureLayer,function(result, error) {
        if(result) {
          console.log("Layer has been successfully rebuilt while offline!");
        }
      });

      _layers.push(newFeatureLayer);
    }
  }

**Comment by pstevlingson** [comment]
Document was loaded from Application Cache with manifest http://server03.windlake.com/LeakSurveyCollector/leaksurvey.appcache
Application Cache Checking event
Application Cache Error event: Manifest fetch failed (6) http://server03.windlake.com/LeakSurveyCollector/leaksurvey.appcache
appCacheManager.js enabled
CACHE EVENT: {}
CACHE ERROR: {}
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png? net::ERR_INTERNET_DISCONNECTED
STATE IS: false
database opened successfully
init editsStore.js
GET http://js.arcgis.com/3.14compact/esri/images/map/logo-med.png net::ERR_INTERNET_DISCONNECTED
looking for tile 16 24695 19243
LIBRARY ONLINE false
looking for tile 16 24696 19243
LIBRARY ONLINE false
looking for tile 16 24695 19244
LIBRARY ONLINE false
looking for tile 16 24696 19244
LIBRARY ONLINE false
looking for tile 16 24695 19245
LIBRARY ONLINE false
looking for tile 16 24696 19245
LIBRARY ONLINE false
looking for tile 16 24695 19246
LIBRARY ONLINE false
looking for tile 16 24696 19246
LIBRARY ONLINE false
looking for tile 16 24695 19247
LIBRARY ONLINE false
looking for tile 16 24696 19247
LIBRARY ONLINE false
looking for tile 16 24695 19248
LIBRARY ONLINE false
looking for tile 16 24696 19248
LIBRARY ONLINE false
looking for tile 16 24695 19249
LIBRARY ONLINE false
looking for tile 16 24696 19249
LIBRARY ONLINE false
looking for tile 16 24695 19250
LIBRARY ONLINE false
looking for tile 16 24696 19250
LIBRARY ONLINE false
Tile Layer initialized for offline. App state is: up
database opened successfully
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=702754016 net::ERR_INTERNET_DISCONNECTED
GET http://js.arcgis.com/3.14compact/esri/dijit/images/ajax-loader.gif net::ERR_INTERNET_DISCONNECTED
GET http://js.arcgis.com/3.14compact/esri/dijit/images/popup.png net::ERR_INTERNET_DISCONNECTED
GET void:/16/24695/19243 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19243 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19244 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19244 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19245 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19245 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19246 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19246 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19247 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19247 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19248 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19248 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19249 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19249 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24695/19250 net::ERR_UNKNOWN_URL_SCHEME
GET void:/16/24696/19250 net::ERR_UNKNOWN_URL_SCHEME
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19243
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19243
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19244
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19244
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19245
TILE RETURN false, undefined
tile is not in the offline store http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19245
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19246
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19246
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19246
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19246
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19247
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19247
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19247
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19247
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19248
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19248
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19248
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19248
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19249
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19249
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19249
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19249
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19250
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24695/19250
TILE RETURN true, http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19250
found tile offline http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/16/24696/19250
Unable to init PhantomLayer
Uncaught TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'length' of undefined
    at d.addLayers (http://js.arcgis.com/3.14compact/init.js:308:283)
    at declare._initializeApplication (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:193:26)
    at null.<anonymous> (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:119:26)
    at g.hitch (http://js.arcgis.com/3.14compact/init.js:167:296)
    at k (http://js.arcgis.com/3.14compact/init.js:189:431)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357)
    at x.reject (http://js.arcgis.com/3.14compact/init.js:192:143)
    at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:103)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357) "TypeError: Cannot read property 'length' of undefined
    at d.addLayers (http://js.arcgis.com/3.14compact/init.js:308:283)
    at declare._initializeApplication (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:193:26)
    at null.<anonymous> (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:119:26)
    at g.hitch (http://js.arcgis.com/3.14compact/init.js:167:296)
    at k (http://js.arcgis.com/3.14compact/init.js:189:431)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357)
    at x.reject (http://js.arcgis.com/3.14compact/init.js:192:143)
    at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:103)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357)
    ----------------------------------------
    rejected at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:89)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357)
    at x.reject (http://js.arcgis.com/3.14compact/init.js:192:143)
    at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:103)
    at m (http://js.arcgis.com/3.14compact/init.js:189:357)
    at x.reject (http://js.arcgis.com/3.14compact/init.js:192:143)
    at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:89)
    ----------------------------------------
Error
    at f.then.b.then [as then] (http://js.arcgis.com/3.14compact/init.js:192:253)
    at verifyOnline [as _verifyOnline] (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:413:54)
    at declare.constructor (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:113:18)
    at new <anonymous> (http://js.arcgis.com/3.14compact/init.js:98:398)
    at http://server03.windlake.com/LeakSurveyCollector/js/main.js:6:17
    at ha (http://js.arcgis.com/3.14compact/init.js:22:473)
    at http://js.arcgis.com/3.14compact/init.js:23:202
    at ia (http://js.arcgis.com/3.14compact/init.js:23:89)
    at fa (http://js.arcgis.com/3.14compact/init.js:23:144)
    at g (http://js.arcgis.com/3.14compact/init.js:25:380)"
TypeError: Cannot read property 'success' of undefined
    at null.<anonymous> (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1162:37)
    at k (http://js.arcgis.com/3.14compact/init.js:189:431)
    at f.then.b.then [as then] (http://js.arcgis.com/3.14compact/init.js:192:308)
    at declare.extend (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1152:41)
    at http://server03.windlake.com/LeakSurveyCollector/js/services/mapservices.js:106:34
    at http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1275:37
    at IDBRequest.objectStoreGraphicRequest.onsuccess (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:3163:17) "TypeError: Cannot read property 'success' of undefined
    at null.<anonymous> (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1162:37)
    at k (http://js.arcgis.com/3.14compact/init.js:189:431)
    at f.then.b.then [as then] (http://js.arcgis.com/3.14compact/init.js:192:308)
    at declare.extend (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1152:41)
    at http://server03.windlake.com/LeakSurveyCollector/js/services/mapservices.js:106:34
    at http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1275:37
    at IDBRequest.objectStoreGraphicRequest.onsuccess (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:3163:17)
    ----------------------------------------
    rejected at a (http://js.arcgis.com/3.14compact/init.js:190:337)
    at k (http://js.arcgis.com/3.14compact/init.js:190:89)
    at f.then.b.then [as then] (http://js.arcgis.com/3.14compact/init.js:192:308)
    at declare.extend (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1152:41)
    at http://server03.windlake.com/LeakSurveyCollector/js/services/mapservices.js:106:34
    at http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1275:37
    at IDBRequest.objectStoreGraphicRequest.onsuccess (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:3163:17)
    ----------------------------------------
Error
    at f.then.b.then [as then] (http://js.arcgis.com/3.14compact/init.js:192:253)
    at declare.extend (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1152:41)
    at http://server03.windlake.com/LeakSurveyCollector/js/services/mapservices.js:106:34
    at http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:1275:37
    at IDBRequest.objectStoreGraphicRequest.onsuccess (http://server03.windlake.com/LeakSurveyCollector/js/offline/offline-edit-src.js:3163:17)"
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=542998149 net::ERR_INTERNET_DISCONNECTED
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=195009355 net::ERR_INTERNET_DISCONNECTED
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=131444003 net::ERR_INTERNET_DISCONNECTED
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=902590869 net::ERR_INTERNET_DISCONNECTED
GET http://server03.windlake.com/LeakSurveyCollector/images/tiny-image.png?_=695822580 net::ERR_INTERNET_DISCONNECTED

**Comment by pstevlingson** [comment]
The tile library seems to work in ie11 without issues.  Do you have the list of limitations in ie (specifically ie11) that cause problems for the offline library?  

I'm told our current utility client uses Microsoft rugged books in the field and supports ie11 as their corporate standard browser.   They currently do not support chrome, safari or firefox.

**Comment by andygup** [comment]
>> When I run the application in IE11, the onsuccess handler at line 3229 is being executed. When I run it in the latest version of chrome it is not.

To make sure I understand, your app runs just fine in IE11 and not in Chrome?

>> Do you have the list of limitations in ie (specifically ie11) that cause problems for the offline library?

Nope, sorry. The main issues at the time had to do with limited IndexedDB support, various JavaScript syntax issues. I also don't have any way to troubleshoot IE 11 or Edge issues.

----------------------------

What version of the library are you using? The version number is at the top of each library. The latest and greatest is v2.13.1. Since the line numbers won't match up between versions, I'm not able to match up the error message line numbers from the console.log.

Thanks for the console.log. At least for this round of tweaks, the good news is I don't see any issues related to the OfflineFeaturesManager library initializing. 

There is one glaring item that hints it needs further looking into. It's related to tile layer in `appcontroller.js` line 193. After that there is a cascade of other errors. Can you take a took at that and see if this is the primary event triggering some or all of the other issues?

The deferred errors you are seeing very likely could be because something else broke before or during the asynchronous action began, and that issue then prevented the deferred from being resolved or gracefully rejected.

```js

Unable to init PhantomLayer
Uncaught TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'length' of undefined
at d.addLayers (http://js.arcgis.com/3.14compact/init.js:308:283)
at declare.initializeApplication (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:193:26)
at null. (http://server03.windlake.com/LeakSurveyCollector/js/controllers/appcontroller.js:119:26)

```

**Comment by pstevlingson** [comment]
The appcontroller.js module is failing at line 193 because offlineFeaturesManager.getFeatureCollections is not returning the stored layer in the indexeddb.

Yesterday I was using offline-editor-js - v2.13.0 - 2015-08-10.    I just downloaded v.2.13.1.  I will perform some more testing and give you an update later today.

If there is any chance in the future that you could support ie11 or edge that would be great.    However, the clients might be open to using chrome.

**Comment by andygup** [comment]
>> If there is any chance in the future that you could support ie11 or edge that would be great.

No, I don't see any chance of IE11 support. Edge is a possibility as some point in the future if there are more requests. So far, you're the only person who's requested Edge, and only one or two other people have requested IE support in the last two years. The vast majority of implementations for this repo are Android and iOS smartphones and tablets. 

**Next steps**

* Can you verify: are you wanting an intermittent offline for a full offline workflow? If you aren't sure of the difference here's a [blog post](http://www.andygup.net/offline-javascript-part-3-intermittent-offline/) I wrote. The pattern you are showing me above hints at full offline, but I wanted to be 100% certain.

* When are you seeing these errors: when the application first loads online, or after an offline restart?

* Review the life-cycle patterns in [appcache-features.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html).

* Pay particular attention to the fact that offlineFeaturesManager doesn't get initialized until after feature layers `update-end` event as shown [here](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html#L325).

* Place a break point [here](https://github.com/Esri/offline-editor-js/blob/master/dist/offline-edit-src.js#L1145) and let's verify the error message and see if it hints at anything. Looks like we missed printing that error message to console. I'll add that as a minor TO-DO. 

     I have a strong suspicion that the map is not initialized by the time you run `offlineFeaturesManager.extend()`. The following error certain points a finger in that direction because the error is happening [here](https://github.com/Esri/offline-editor-js/blob/master/dist/offline-edit-src.js#L1142) and it's in the `esri.Map.addLayers()` method. If the map isn't initialized then the offlineFeaturesManager library cannot add the phantom graphics layer to it. There's also a good chance the feature layers aren't initialized, as well. Any of these issues could explain what you're seeing.

```js

Uncaught TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'length' of undefined
at d.addLayers (http://js.arcgis.com/3.14compact/init.js:308:283)

```

**Comment by pstevlingson** [comment]
I looked into the initialization problem and that does appear to be the root cause of the problem.    I am creating and extending the layer before even adding it to the map.   It looks like I have to add the layer to the map, wait for it to initialize via the "layers-add-result" map event, then the "_map" variable will be set on the layer and "extend" will function properly.    

It might be handy to put a check for a null _map somewhere in extend function and warn that the map has to be initialized if its not.  The _initPhantomLayer function seems to be the exact location where it was failing because of the null _map.

That makes sense about Android and iOS.     If the library appears to work with IE11 I'll use it, realizing that if I run into problems I'm on my own.

Thanks for your help on this.

**Comment by andygup** [comment]
Glad you got it going. I agree on the null map check, that's an excellent idea since this is a common issue. I'll put a fix in place.
