### ISSUE TITLE
Double Applyedits

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#406]
We are seeing two points added to the backend for a single (edit) add feature. Setting a break point in offline-edit.js at line #394, we only see only one applyEdit() request.

**Comment by andygup** [comment]
Hey Matt, I'll take another look. I saw similar behavior while the app was online yesterday which may be the key to solving this one.

Observation: After adding a new point, I saw one edit request pass thru the offline-editor-js library. However, two graphics were created and stacked precisely on top of each other, each with a unique OBJECTID. The only way for an OBJECTID to be created is during a successful edit request roundtrip to the feature service.

**Comment by webmapsolutions** [comment]
Thanks Andy. We've been trying to trace this through, as you see we are
using the ArcGIS JS editor widget, with offline library. Having trouble
seeing the source of the problem.

On 20 August 2015 at 09:15, Andy <notifications@github.com> wrote:

> Hey Matt, I'll take another look. I saw similar behavior while the app was
> online yesterday which may be the key to solving this one.
>
> Observation: After adding a new point, I saw one edit request pass thru
> the offline-editor-js library. However, two graphics were created and
> stacked precisely on top of each other, each with a unique OBJECTID. The
> only way for an OBJECTID to be created is during a successful edit request
> roundtrip to the feature service.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/406#issuecomment-133045339>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by andygup** [comment]
Okay, I think I got it. The problem seems to be that `OfflineFeaturesManager.goOnline()` is being called twice, concurrently by your app. 

I can see the console.log message "offlineFeaturesManager going online" get printed twice, and I verified it with breakpoints. I also confirmed there is only a single edit in the database in my tests and the sync loop is limited to the number of edits in the database as shown [here](https://github.com/Esri/offline-editor-js/blob/master/lib/edit/offlineFeaturesManager.js#L1669). So, the sync loop was only syncing one edit per `goOnline()` request. 

What's going wrong? `goOnline()` is asynchronous. The best I can tell, your app is firing off a second concurrent `goOnline()` request before the first async request completes. That's a problem because the second request is able to successfully query the database and see the pending edit. This can happen because the first `goOnline()` async operation hasn't had a chance to successfully complete and then clean the database. It's a 100% classic async problem, and the second most common reason behind async app bugs.

I recommend scouring your code and making sure there is only one entry point for a `goOnline()` request to be issued.

**Comment by webmapsolutions** [comment]
Excellent, thanks Andy. We will start scouring.

On 20 August 2015 at 10:25, Andy <notifications@github.com> wrote:

> Okay, I think I got it. The problem seems to be that
> OfflineFeaturesManager.goOnline() is being called twice, concurrently by
> your app.
>
> I can see the console.log message "offlineFeaturesManager going online"
> get printed twice, and I verified it with breakpoints. I also confirmed
> there is only a single edit in the database in my tests and the sync loop
> is limited to the number of edits in the database as shown here
> <https://github.com/Esri/offline-editor-js/blob/master/lib/edit/offlineFeaturesManager.js#L1669>.
> So, the sync loop was only syncing one edit per goOnline() request.
>
> What's going wrong? goOnline() is asynchronous. The best I can tell, your
> app is firing off a second concurrent goOnline() request before the first
> async request completes. That's a problem because the second request is
> able to successfully query the database and see the pending edit. This can
> happen because the first goOnline() async operation hasn't had a chance
> to successfully complete and then clean the database. It's a 100% classic
> async problem, and the second most common reason behind async app bugs.
>
> I recommend scouring your code and making sure there is only one entry
> point for a goOnline() request to be issued.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/406#issuecomment-133066221>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by webmapsolutions** [comment]
Andy

This is what I am seeing:

- On startup we extend the two feature layers (to offline enable).
- Next disconnect from wireless.
- Next restart browser (so now in full offline mode)
- Make an edit (add new feature).
- Reconnect to wireless.
- Go back online (by hitting online button).
- This then calls the toggleConnection method which calls goOnline for each
(extended) feature layer. We have two layers so goOnline  is called for
each layer (so twice in this case respectively). This seems to be the
problem. It almost appears that this is flushing the database twice of all
edits? Should we wait for (applyEdits) success response from ArcGIS before
executing the next goOnline  call?

On 20 August 2015 at 10:32, Matt Sheehan <matt@webmapsolutions.com> wrote:

> Excellent, thanks Andy. We will start scouring.
>
> On 20 August 2015 at 10:25, Andy <notifications@github.com> wrote:
>
>> Okay, I think I got it. The problem seems to be that
>> OfflineFeaturesManager.goOnline() is being called twice, concurrently by
>> your app.
>>
>> I can see the console.log message "offlineFeaturesManager going online"
>> get printed twice, and I verified it with breakpoints. I also confirmed
>> there is only a single edit in the database in my tests and the sync loop
>> is limited to the number of edits in the database as shown here
>> <https://github.com/Esri/offline-editor-js/blob/master/lib/edit/offlineFeaturesManager.js#L1669>.
>> So, the sync loop was only syncing one edit per goOnline() request.
>>
>> What's going wrong? goOnline() is asynchronous. The best I can tell,
>> your app is firing off a second concurrent goOnline() request before the
>> first async request completes. That's a problem because the second request
>> is able to successfully query the database and see the pending edit. This
>> can happen because the first goOnline() async operation hasn't had a
>> chance to successfully complete and then clean the database. It's a 100%
>> classic async problem, and the second most common reason behind async app
>> bugs.
>>
>> I recommend scouring your code and making sure there is only one entry
>> point for a goOnline() request to be issued.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Esri/offline-editor-js/issues/406#issuecomment-133066221>
>> .
>>
>
>
>
> --
>
> *Matt Sheehan | WebMapSolutions*
>
> Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
> <Email%3Amatt@webmapsolutions.com>
>
>
>


-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by andygup** [comment]
Ah gotcha. You should only call `goOnline()` once to sync **all** edits, even if you have multiple feature layers. The only time you would ever need to call it again is if there were sync errors.

The correct configuration is to have only one database instance per app. That single instance contains all edits for all feature layers  as initialized via `OfflineFeaturesManager.extend()`. Multiple feature layers share a single database instance, that's by design. The database is indexed by a UUID that distinguishes between different feature layers and keeps everything straight.

**Comment by webmapsolutions** [comment]
Okay, great. That's a huge help. Looking at it that now makes sense. I'll
tweek the code to ensure we only make one call. Thx

On 20 August 2015 at 11:12, Andy <notifications@github.com> wrote:

> Ah gotcha. You should only call goOnline() once to sync *all* edits, even
> if you have multiple feature layers. The only time you would ever need to
> call it again is if there were sync errors.
>
> The correct configuration is to have only one database instance per app.
> That single instance contains all edits for all feature layers as
> initialized via OfflineFeaturesManager.extend(). Multiple feature layers
> share a single database instance, that's by design. The database is indexed
> by a UUID that distinguishes between different feature layers and keeps
> everything straight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/406#issuecomment-133079358>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by andygup** [comment]
I'll temporarily leave this open as a documentation TO-DO. Clarify the points mentioned above related to the use of `goOnline()`.

**Comment by webmapsolutions** [comment]
That's great Andy. I think that will help others who are looking to
implement the library.

On 20 August 2015 at 11:26, Andy <notifications@github.com> wrote:

> I'll temporarily leave this open as a documentation TO-DO. Clarify the
> points mentioned above related to the use of goOnline().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/406#issuecomment-133083272>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>
