### ISSUE TITLE
phantomAdd.getNode() returning null

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#407]
We are seeing an issue with editing in full offline mode. The workflow is as follows:

- Open the app online 
- Next disconnect from wireless.
- Next restart browser (so now in full offline mode)  
- Make an edit (add new feature). We have two feature layers offline enabled. One or other seems to be failing (no point feature added to map and no attribute inspector)

Looking at console we see . 

Uncaught TypeError: Cannot read property 'setAttribute' of null
m.set	@	dojo.js:139
(anonymous function)	@	offline-edit.js:977
transaction.oncomplete	@	offline-edit.js:2500

With a breakpoint at line 977 in offline-edit.js we see phantomAdd.getNode() is returning null

**Comment by andygup** [comment]
Is there a chance you are accidentally running two instances of OfflineFeaturesManager, one for each feature layer? 

There should be only one instance of OfflineFeaturesManager per application, and it can then `extend()` multiple feature layers. However, the library is behaving in a way that implies each of the two feature layers is running under a separate instance. For example, each new edit has a unique temporary id and I'm seeing duplication of that temp id between the layers. That would partly explain some of the odd behavior between the two.

**Comment by webmapsolutions** [comment]
Looks like that might be the problem Andy. I'm seeing two calls to new
O.esri.Edit.OfflineFeaturesManager().

On 20 August 2015 at 12:26, Andy <notifications@github.com> wrote:

> Is there a chance you are accidentally running two instances of
> OfflineFeaturesManager, one for each feature layer?
>
> There should be only one instance of OfflineFeaturesManager per
> application, and it can then extend() multiple feature layers. However,
> the library is behaving in a way that implies each of the two feature
> layers is running under a separate instance. For example, each new edit has
> a unique temporary id and I'm seeing duplication of that temp id between
> the layers. That would partly explain some of the odd behavior between the
> two.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/407#issuecomment-133109227>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by andygup** [comment]
Matt, did this solve the issue?

**Comment by webmapsolutions** [comment]
You can close it Andy. This is a bug in our implementation. Thanks.

On 1 September 2015 at 12:12, Andy <notifications@github.com> wrote:

> Matt, did this solve the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/407#issuecomment-136815574>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>
