### ISSUE TITLE
Offline phonegap application with tpk fie

### ISSUE THREAD

**Issue by kountouretis** [Esri/offline-editor-js#415]
I strat to develop an android application using phonegap. Also i have already done a map with arcgis with some points.Now i am in the part that i must use the tpk file which is the map and the database which is in csv format ( In database there are some points and names of places that i want to show in the map ) . I don't understand how to use these two files(tpk file and csv) together offline to build mt app.

**Comment by andygup** [comment]
Hi Antonis, I think I understand what you are asking. 

My suggestion would be to create an ArcGIS Online FeatureLayer using the csv data. Here's a [document](http://doc.arcgis.com/en/arcgis-online/share-maps/publish-features.htm) that describes the steps. You can create a free [ArcGIS Online developer account](https://developers.arcgis.com/en/plans/) to test this out. Once your csv data is in a FeatureLayer that you will be able to use it with a tpk file with this library.

The `offline-editor-js` library does not support using a [CSVLayer](https://developers.arcgis.com/javascript/jsapi/csvlayer-amd.html). It only supports [FeatureLayer](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html). I'll make a note to clarify this in the documentation.

**Comment by andygup** [comment]
Antonis, how's it going with getting the CSV figured out?

**Comment by kountouretis** [comment]
Hi AndyThanks for you reply.
I saw the https://github.com/andygup/offline-editor-js  and i saw also the tpk-layer.html  . I will find way to convert the csv file to json or other way and take the data i want. Especially my problem is if possible to plot (points,popups etc.) on tpk file with javascript. 
This is  html/javascript code that i plot points. i want to do the same with tpk file
<!DOCTYPE html><html>  <head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">    <title></title>    <link rel="stylesheet" href="//js.arcgis.com/3.7/js/esri/css/esri.css">    <style>      html, body, #map {        height: 100%; width: 100%; margin: 0; padding: 0;       }    </style>    <script src="//js.arcgis.com/3.7/"></script>    <script>      var map;          require([        "esri/map",         "esri/geometry/Point",        "esri/symbols/SimpleMarkerSymbol",        "esri/symbols/PictureMarkerSymbol",        "esri/graphic",         "esri/layers/GraphicsLayer",        "dojo/domReady!"      ], function(        Map, Point, SimpleMarkerSymbol, PictureMarkerSymbol, Graphic, GraphicsLayer      ) {        map = new Map("map", {          basemap: "streets",          center: [-88.21,42.21],          zoom: 10        });        map.on("load", function() {          var gl = new GraphicsLayer();          var p = new Point(-88.380801, 42.20670);                    var s = new SimpleMarkerSymbol().setSize(30);          var g = new Graphic(p, s);          gl.add(g);                             var p2 = new Point(-88.380801, 42.10670);          var pms = new PictureMarkerSymbol({"url":"http://static.arcgis.com/images/Symbols/Basic/YellowStickpin.png",                                             "height":30,    "width":30}); var g2 = new Graphic(p2, pms);                gl.add(g2);          map.addLayer(gl);        });      });    </script>  </head>  <body>    <div id="map"></div>  </body></html>
Date: Mon, 19 Oct 2015 08:07:42 -0700

**Comment by andygup** [comment]
@kountouretis for information on plotting points please read the ArcGIS API for JavaScript documentation under [Guide tab > Graphics and Features Layers](https://developers.arcgis.com/javascript/jshelp/inside_graphics.html). There is also a documentation section right below that in the left hand table of contents called Popups and InfoWindows.

![image](https://cloud.githubusercontent.com/assets/510440/10731129/7c3958ee-7bb9-11e5-88a7-8c8f29debd89.png)

**Comment by andygup** [comment]
Antonis, I'll close this for now. Feel free to either reopen this for a related issue or open a new issue if you get stuck.
