### ISSUE TITLE
indexDB Issue Loading Multiple Private Layers

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#416]
We are using 6 private layers in an offline app. After successfully loading the map and layers when we use Chrome tools to look at the resources we do not see all the layers in indexDB. We initially suspected flakiness in Chrome tools causing all layers not to be shown but on further inspection it would appear all layers are simply not there.

**Comment by andygup** [comment]
Matt, I got the file you emailed. I'll take a look this afternoon.

In the meantime, there's another sample app that demonstrates the [concept of using multiple layers](https://github.com/Esri/offline-editor-js/blob/master/samples/draw-pointlinepoly-offline.html#L256) that you might take a peek at.

**Comment by webmapsolutions** [comment]
Thanks Andy. I've done some tests on this code example, and I'm
consistently seeing no layers in indexDB. Again this might be poor
reporting from Chrome tools but hard reloads and indexdb refresh still give
me an empty feature store ..

On 22 October 2015 at 11:52, Andy <notifications@github.com> wrote:

> Matt, I got the file you emailed. I'll take a look this afternoon.
>
> In the meantime, there's another sample app that demonstrates the concept
> of using multiple layers
> <https://github.com/Esri/offline-editor-js/blob/master/samples/draw-pointlinepoly-offline.html#L256>
> that you might take a peek at.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/offline-editor-js/issues/416#issuecomment-150305049>
> .
>



-- 

*Matt Sheehan | WebMapSolutions*

Mobile: 801-733-0723 | Email: matt@webmapsolutions.com
<Email%3Amatt@webmapsolutions.com>

**Comment by andygup** [comment]
Matt, in the sample app you sent the primary issue is your code is overwriting the `dataStore` every time `extend()` is called for each new feature layer. `dataStore` uses a LIFO (Last in, first out) policy. The very last object written to the `dataStore` will overwrite the previous object. 

When manually creating a `dataStore` simply append any additional properties for each additional feature layer that's extended. Here's a psuedo-example:

```javascript

// In this example we have an existing dataStore and
// then append Layer3 to it.
var dataStore = {
        "featureLayerJSON_Layer2": { . . . },
        "featureLayerJSON_Layer1": { . . . },
        "zoom": 7,
        "centerPt": { . . . }
    }

dataStore.featureLayerJSON_Layer3 = featureLayer.toJson();

offlineFeaturesManager.extend(layer3,function(success, error){
    if(success){
        console.log("Layer has been extended for offline use.");
    }
}, dataStore);
```
