### ISSUE TITLE
Unable to extend multiple feature layers

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#419]
There appears to be a bug affecting multiple layers in full offline mode. We are seeing not all layers being written to indexdb.

**Comment by andygup** [comment]
It looks like a bug. The `layer.extend()` callback is returning **before** the database add/update is complete. It's very possible if you do multiple `extend()` operations that the current add/update may overwrite or interrupt the previous operation causing a skip to occur. 

You wouldn't notice a problem if you are only using a single feature layer.

I'll see about getting a fix implemented asap.
