### ISSUE TITLE
Working with multiple Feature layers

### ISSUE THREAD

**Issue by dpinart** [Esri/offline-editor-js#436]
Hi

I'm trying to extend a couple of layers with no success.Since FEATURE_LAYER_JSON_ID is alway set to feature-layer-object-1001 only the last added layer gets persisted in the browser's IndexedDB. Is it possible to work with more than 1 FeatureLayer? If so, can somebody point me to a demo or doc?

Thanks

**Comment by andygup** [comment]
>> Is it possible to work with more than 1 FeatureLayer?

Hi, for now there is one sample that demonstrates the basic pattern. the [appcache-twofeatureslayer-noedit.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-twofeatureslayer-noedit.html) sample shows how to do it for full offline with `OfflineEditAdvanced`. You can also use a similar pattern for intermittent offline with the `OfflineEditBasic` library. 

I recommend checking out the documentation [here](http://esri.github.io/offline-editor-js/demo/api-doc.html) and the [How to use the advanced edit library](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseofmadvancedlibrary.md).

I also added a label to this issue that use of the edit library with multiple layers needs to have better documentation.

**Comment by dpinart** [comment]
Thanks Andy

I was using an older version I download some weeks ago. I just saw the new version from 4 weeks ago and the two features layers demo.

Gonna try the proposed pattern

**Comment by dpinart** [comment]
Can I combine tpk files with FeatureLayers?

**Comment by andygup** [comment]
Yep, you can combine tpk's with OfflineEditAdvanced.
