### ISSUE TITLE
OfflineTilesAdvanced does not load tiles when app starts offline

### ISSUE THREAD

**Issue by dpinart** [Esri/offline-editor-js#443]
Hi,

I'm developping an app for apache cordova. Offline tiles work fine if user launches de app when the device is still online and downloads the tiles for the map. After that, if the device goes offline and the user navigates again to the map view, the map loads tiles from the local storage.

However, if app starts when the device is already offline and the user navigates to the map view despite the IndexedDB still contains the tiles for the map, no tiles are shown.

I guess this may be a frequent question, but I've not been able to find any issue related.

Thanks

**Comment by andygup** [comment]
@dpinart Hi, try the following steps:

1. Make sure to review the [How to use](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseofmadvancedlibrary.md) documentation.
2. You'll need to build an application cache file, more details are available [here](https://github.com/Esri/offline-editor-js/wiki/Working-with-Application-Cache).
3. Compare your app life-cycle to the full offline samples such as [appcache-features.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-features.html)
4. Run your app as a stand-alone web app **without** cordova, or use remote debugging.
5. Look in the browser console for any errors. Errors that you aren't able to figure out post a screenshot of them here. If there's a specific error then we can dig into that and see what's going on.

**Comment by andygup** [comment]
@dpinart oops, here's the link to the How to Use for offline tiles: https://github.com/Esri/offline-editor-js/blob/master/doc/howtousetiles.md.

**Comment by dpinart** [comment]
@andygup Thanksfor your quick response. I'm not sure I understand all these steps. 

Watching code at offline-tiles-advanced.src.js I can see that OfflineTilesAdvanced in constructor it first initializes the TileStore. If TileStore is successfully initialized it then calls the private method _getTileInfoPrivate. This method tries to perform an ajax request to the map url in order to get tiles info. As app is offline, the xmlhttprequest obviously, fails and therefore tileInfo is not created.

I guessed in some way this tile info was being stored locally in order to be able to start from offline

**Comment by dpinart** [comment]
Hi

I have modified a little bit the OfflineTilesAdvanced class. I'm basically storing the the tileInfo downloaded on _getTileInfoPrivate method like 'localStorage['__' + self.DB_OBJECTSTORE_NAME] = result. This way, if OfflineTilesAdvanced is created while offline I can call _parseTileInfo with the tileInfo stored previously in localStorage.

Not sure if its the most elegant option but it works really great

**Comment by andygup** [comment]
@dpinart I'm not sure I understand what you did, but if you are happy please close this issue.

>> I guessed in some way this tile info was being stored locally in order to be able to start from offline

The library internally uses IndexedDB which should be able to store between 75MB - 100MB in tiles. It looks like you may be using localStorage which is severely limited to 5MBs or less. 

>>This method tries to perform an ajax request to the map url in order to get tiles info. As app is offline, the xmlhttprequest obviously, fails and therefore tileInfo is not created.

I'm guessing the reason your tile requests are failing offline is because you didn't set up an application cache.

**Comment by dpinart** [comment]
@andygup you're right, I haven't setup an application cache. I know understant what the appcache is used for in this scenario. appcahce-tiles .appcache has this entry 
//server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer?f=pjson 
so the xmlHttpRequest is going to the application cache when offline to download tile info!!
