### ISSUE TITLE
Apps need restart to Populate indexDB

### ISSUE THREAD

**Issue by webmapsolutions** [Esri/offline-editor-js#447]
Testing the appcache-twofeatureslayer-noedit.html we notice indexDB does not get populated on first load, but needs a reload

http://webmapsolutions.com/offline-editor-v3/samples/appcache-twofeatureslayer-noedit.html

Steps to reproduce:

1. Clear browser history and clear indexDB
2. Load the app. Notice indexdb is empty
3. Reload app. Indexdb is now populated.

**Comment by andygup** [comment]
@webmapsolutions I'm unable to duplicate. I tried Chrome on both a mac and on a windows machine. 

Try bolting in this block of code at line 377, and then give it a another try. Sometimes the console viewer for IndexedDB is a bit flaky and won't accurately reflect database contents. This bit of code will simply grab the featureCollections straight out of the database and write it to console. If the featureCollections are there that verifies the layer initialized correctly:

```javascript

offlineEdit.getFeatureCollections(function(success, message){
    console.log("getFeatureCollections: " + success + ", " +
            message.featureCollections.length + ", " +
            message.id);
});

```

Here's what I'm seeing in console:

![image](https://cloud.githubusercontent.com/assets/510440/12826897/743cc808-cb3a-11e5-9f02-2c02ed0cfae0.png)

**Comment by webmapsolutions** [comment]
I see it consistently Andy in this sample. We are seeing the same
behaviour in the work order (WO) app. The WO's only load (when indexDB is
cleared using Chrome tools resources->clear) after a restart. When you
have time I can do a quick screenshare.



> @webmapsolutions I'm unable to duplicate. I tried Chrome on both a mac and
> on a windows machine.
>
> Try bolting in this block of code at line 377, and then give it a another
> try. Sometimes the console viewer for IndexedDB is a bit flaky and won't
> accurately reflect database contents. This bit of code will simply grab
> the featureCollections straight out of the database and write it to
> console. If the featureCollections are there that verifies the layer
> initialized correctly:
>
> ```javascript
>
> offlineEdit.getFeatureCollections(function(success, message){
>     console.log("getFeatureCollections: " + success + ", " +
>             message.featureCollections.length + ", " +
>             message.id);
> });
>
> ```
>
> Here's what I'm seeing in console:
>
> ![image](https://cloud.githubusercontent.com/assets/510440/12826897/743cc808-cb3a-11e5-9f02-2c02ed0cfae0.png)
>
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Esri/offline-editor-js/issues/447#issuecomment-180017775


--Matt

Matt Sheehan
Principal | WebMapSolutions
801.733.0723 | www.webmapsolutions.com

**Comment by andygup** [comment]
Did you test the sample app with the code snippet I posted above? Please post a screenshot of the console output after bolting in the code snippet.

**Comment by webmapsolutions** [comment]
I was too early in sending my last response Andy. I added this code and
see the featureCollections are in IndexDB. How very curious.



> @webmapsolutions I'm unable to duplicate. I tried Chrome on both a mac and
> on a windows machine.
>
> Try bolting in this block of code at line 377, and then give it a another
> try. Sometimes the console viewer for IndexedDB is a bit flaky and won't
> accurately reflect database contents. This bit of code will simply grab
> the featureCollections straight out of the database and write it to
> console. If the featureCollections are there that verifies the layer
> initialized correctly:
>
> ```javascript
>
> offlineEdit.getFeatureCollections(function(success, message){
>     console.log("getFeatureCollections: " + success + ", " +
>             message.featureCollections.length + ", " +
>             message.id);
> });
>
> ```
>
> Here's what I'm seeing in console:
>
> ![image](https://cloud.githubusercontent.com/assets/510440/12826897/743cc808-cb3a-11e5-9f02-2c02ed0cfae0.png)
>
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Esri/offline-editor-js/issues/447#issuecomment-180017775


--Matt

Matt Sheehan
Principal | WebMapSolutions
801.733.0723 | www.webmapsolutions.com

**Comment by andygup** [comment]
Yep, I'm fairly certain the library would throw an error if it couldn't create the feature collection and add it to the database.

My advice: use the debugger to walk thru every single step of the application's initialization sequence before, during and after WO initialization. Check all inputs and outputs to see if they are valid. That's the best way to find this bugger of a problem.

**Comment by webmapsolutions** [comment]
Thanks Andy. I'll close this issue.
