### ISSUE TITLE
Array.prototype.sortNumber messes up looping through arrays

### ISSUE THREAD

**Issue by hoesli** [Esri/offline-editor-js#458]
The following line breaks looping through arrays with a for...in loop anywhere in an application when using offline-editor-js

```
//For calculating minZoom and maxZoom
96ea123
@andygup extended jshint
andygup authored on 11 Jul 2015

Array.prototype.sortNumber = function(){return this.sort(function(a,b){return a - b;});};
```
Do you see a way to remove this?

Thanks
Christoph

**Comment by andygup** [comment]
Very interesting. That used to have a purpose, but it's not being used anywhere in the OfflineTilesAdvanced.js library anymore. I'll create a new build, run some tests to make sure all's good, then push it up.
