### ISSUE TITLE
Use secure origins with Application Cache and Chrome

### ISSUE THREAD

**Issue by andygup** [Esri/offline-editor-js#495]
FYI, if you are using Application Cache (a.k.a Cache Manifest or AppCache) you'll need to start migrating to HTTPS.

Reference: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by Jones417** [comment]
Can anyone confirm that appcache works on secure origins?

This link suggests appcache is deprecated for all origins.

https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by andygup** [comment]
@Jones417 Appcache works on secure origins. Also here's some additional info: http://www.andygup.net/application-cache-is-not-gone-oh-my-or-is-it/.

**Comment by Jones417** [comment]
@andygup Thank you very much for your time and reply!
