### ISSUE TITLE
Can't open project from html file.

### ISSUE THREAD

**Issue by RawenW** [Esri/offline-editor-js#498]
Hello, i am very interesting about this solution, but i dont know what i am doing wrong. I downloaded this project on https://github.com/Esri/offline-editor-js and i wanted open tpk-layer.html file (in chrome/firefox/ie). Everytime i get some errors after start and nothing works..

![error](https://cloud.githubusercontent.com/assets/26795627/24509528/dcea79fa-1566-11e7-9850-aa2072d5c71d.png)

But, when i try open it from internet (on http://esri.github.io/offline-editor-js/samples/tpk-layer.html) everything working great. What am i doing wrong? Need it something special for work?

thank for every reply!

**Comment by andygup** [comment]
@RawenW make sure you run the entire github project from within a webserver directory. Also make sure to always use http or http to run the app, for example: http://localhost/offline-editor-js/samples/tpk-layer.html. Let me know if that fixes it or not?

**Comment by RawenW** [comment]
@andygup Thanks for reply!
That can be the problem. My goal is create .html file (with .js, .tpk and .css files), which will works on every pc where is not internet (full offline). That will look like desktop application, where users will be able work with map and export some data to xml. I can't use for this purpose some Runtime SDK. Is even possible create .html file, which will be able work with map (.tpk file) without the internet, i mean like desktop application?

**Comment by tumenor** [comment]
Hi,

Without much knowledge about the issue, I recommend using Electron which could solve this for you. Atleast you'd get a full desktop application out of it, without the normal limitations of an offline html file.

**Comment by RawenW** [comment]
@tumenor Thanks for idea, but that is not exactly what i want. I have my own application, which is able shows .html files and gives user some utilities. But, for that i need to have workable .html file.

**Comment by andygup** [comment]
@RawenW For plain old JavaScript applications that aren't using Electron that need to work cross-browser, the correct approach is to Application Cache (a.k.a AppCache or Cache Manifest). All the fully offline samples in this repo use Application Cache. 

Service Workers is another alternative, but that approach doesn't support [Windows or iOS](http://caniuse.com/#search=service%20workers).

Here are couple of links that will help:
- [Working with Application Cache](https://github.com/Esri/offline-editor-js/wiki/Working-with-Application-Cache) 
- [Mozilla - Using Application Cache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) and you can ignore the warnings and deprecation notices. 
- [Application cache is not one, or is it? Oh my!](http://www.andygup.net/application-cache-is-not-gone-oh-my-or-is-it/)

**Comment by RawenW** [comment]
@andygup Thanks! So, if i good understand, i have to have all address to files from "ArcGIS API for JavaScript" added in .appcache right?

**Comment by andygup** [comment]
Sorry for the delay, there's quite a bit more to an .appcache. Have you been able to read the above links? There is also an example [appcache](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-tiles.appcache) and corresponding html file in the `/samples` directory.

**Comment by andygup** [comment]
@RawenW I'm going to go ahead and close this. If you have any additional issues feel free to reopen this or create a new issue.
