### ISSUE TITLE
Loading the application from offline device

### ISSUE THREAD

**Issue by tumenor** [Esri/offline-editor-js#499]
The ArcGis map doesnt initiate when loading the application from an offline device, if I start the device offline and then shut off the internet it works just fine.

I am using Offline Tiles advances

                  tileLayer = new O.esri.Tiles.OfflineTilesAdvanced("******",function(evt){
                      console.log("Offline tile lib is enabled. Application state is: " + areWeOnline);
                  },areWeOnline, responser.data);
                  tileLayer.showBlankTiles = true; // if you don't want to see blank tile indicator images
                  tileLayer.offline.proxyPath = null;

                  tilelayer2 = new O.esri.Tiles.OfflineTilesAdvanced("*******",function(evt){
                      console.log("Offline tile lib is enabled. Application state is: " + areWeOnline);
                  },areWeOnline, responser.data);
                  tilelayer2.showBlankTiles = true; // if you don't want to see blank tile indicator images
                  tilelayer2.offline.proxyPath = null;

                  map.addLayer(tileLayer);
                  map.addLayer(tilelayer2);

areWeOnline
`
               if(window.navigator.connection.type == "none") {
                areWeOnline = false;
                startMap();
              } else {
                startMap();
              }
`

Above the startmap which is:

                 function startMap(){
                  //Make sure map shows up after a browser refresh
                  areWeOnline === true ? zoom = 18 : zoom = 17;

                  map =  new Map("map", {
                    center: [59.911491, 10.757933]
                  });`

Plus the layers above of course.
The response.data are just two variables ive added to the functions, it does not interfere with anything but the url out and works just fine with the cache. My problem is that arcgis doesnt start at all while starting it from offline. The area of the map is just blank.

Log:

>init.js:51 DEPRECATED: dojo/io/iframe Use dojo/request/iframe. -- will be removed in version: 2.0
k.deprecated @ init.js:51
>STATE IS: false
>database opened successfully
>******** Failed to load resource: net::ERR_INTERNET_DISCONNECTED
>_getTileInfoPrivate failed: {"isTrusted":true}
>Offline tile lib is enabled. Application state is: false
>******** Failed to load resource: net::ERR_INTERNET_DISCONNECTED
>_getTileInfoPrivate failed: {"isTrusted":true}
>Offline tile lib is enabled. Application state is: false

I've cencored the servers to keep them private

**Comment by andygup** [comment]
Please confirm your browser and version?

- Have you tried running the sample app [appcache-tiles.html](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-tiles.html) while it's fully offline? Did it work fully offline?

- Experiment with using just one tile layer, at first.

- Did you set up an Application Cache, I wasn't 100% certain? Did you get any Application Cache errors? 

- I do not recommend using the pattern `window.navigator.connection.type` to detect offline conditions. All the offline samples in this repo use [Offline.js](http://github.hubspot.com/offline/docs/welcome/) in combination with a simple HTTP request. Note, the [`verifyOffline()`](https://github.com/Esri/offline-editor-js/blob/master/samples/appcache-tiles.html#L194) pattern being used in `appcache-tiles.html`

**Comment by andygup** [comment]
Hi, any luck on this?

**Comment by andygup** [comment]
@tumenor I'm going to go ahead and close this. If you have additional issues please feel free to reopen or create a new issue.
