### ISSUE TITLE
Uncaught TypeError: onerror is not a function   at FileReader.<anonymous> (offline-tpk-src.js:2427)

### ISSUE THREAD

**Issue by kgloveyou** [Esri/offline-editor-js#504]
#### Expected behavior

- Which offline library are you using (e.g. OfflineEditBasic.js, OfflineTilesAdvanced, etc)? 
offline-tpk-src.js
- What's the offline library version number?
esri-offline-maps - v3.7.0 - 2016-11-01
- Describe what you expected or wanted to happen.
"http://esri.github.io/offline-editor-js/samples/tpk-layer.html",   browse a tpk file about 11G
- What you are trying to achieve?
browse a tpk file about 11G
#### Actual behavior

- Describe what occurs in your code.
it threw a error:"Uncaught TypeError: onerror is not a function   at FileReader.<anonymous> (offline-tpk-src.js:2427)"
- Specifically, what seems to work differently than you intended?
- Provide any error messages you see in the console.
Uncaught TypeError: onerror is not a function   at FileReader.<anonymous> (offline-tpk-src.js:2427)
#### Steps to reproduce the behavior

**We can only help you if we're able to reproduce the behavior you describe above.** Please provide:

0. What operating system, browser and browser version are you using?
win7,chrome 63.0.3239.108
1. Steps to reproduce the behavior
2. A link to an app where we can carry out those steps (either our example pages, your publicly facing app, JSFiddle, JSBin, etc)
3. Relevant code snippet(s) (only if not easily obtained from the above link)

**Comment by andygup** [comment]
@kgloveyou Can you confirm you are trying to use an 11 Gigabyte TPK file? If you are working with TPKs that large you'll need to use one of our [native Runtime SDKs](https://developers.arcgis.com/arcgis-runtime/). Maximum "recommended" TPK size for this library are 50MB - 100MB for mobile browsers and potentially up to 300MB for offline laptop browsers. 

Reference: https://github.com/Esri/offline-editor-js/wiki/FAQ#how-much-data-can-you-store-with-the-library

**Comment by kgloveyou** [comment]
@andygup Thanks! I'm going to develop a mobile app using arcgis for js.So,how to store the offline map data	is a problem for me. I have tried a tpk about 500M ,it works OK.But,when  browsing a tpk file about 11G,I got the error.
Is there any solutions for storing offline map data in developing mobile app by arcgis for js?

**Comment by andygup** [comment]
Closing. Feel free to reopen if needed.
