### ISSUE TITLE
store downloaded tiles in user defined storage 

### ISSUE THREAD

**Issue by amarshilpakar** [Esri/offline-editor-js#505]
how can i store the downloaded tiles in phone storage ? I want to store all the downloaded tiles in my phone storage to work with this rather than index db.

Can it be done?

**Comment by andygup** [comment]
This library uses IndexedDB, however, IndexedDB is also limited in storage capacity. We recommend only storing about 100MB (not MB not GB) to prevent random application crashes. That amount of storage covers only a small geography area. We strongly recommend using the ArcGIS Runtimes for offline tiles.

**Comment by amarshilpakar** [comment]
is there any way to download tpk of the basemap?

**Comment by andygup** [comment]
You can use ArcGIS Pro, or if you don't have Pro you could use https://github.com/Esri/TilePackageKreator

**Comment by andygup** [comment]
Closing...feel free to reopen if needed.
