### ISSUE TITLE
Custom TilesOnly v4

### ISSUE THREAD

**Issue by besLisbeth** [Esri/offline-editor-js#509]
Hi @andygup!

I had a need to create a plugin for ArcGIS js SDK version 4 which have the functionality of TilesOnly from your [demo page](http://esri.github.io/offline-editor-js/demo/).  I used the idea of compressing tiles with the help of [lz-string](https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.js) but totally rewrite the code and the way how tiles are stored in indexedDB.

I'm planning to post this project on GitHub after a while and I'm interested if you are not against it.
I'll write that my project is the side project based on the idea of  `Esri/offline-editor-js`.

**Comment by andygup** [comment]
@besLisbeth thanks for reaching out. Feel free to share it with me privately agup at esri dot com, I'd be interested in learning more. We aren't supporting offline for ArcGIS JS 4.x and depending on the use case it may require special licensing.

**Comment by besLisbeth** [comment]
I'll share it with you, as soon as I finish with demo and documentation. However, it seems strange to me, that this functionality may require special licensing if you can build it based on open-source repositories.

**Comment by andygup** [comment]
@besLisbeth Just to clarify, it's not against the licensing to use the ArcGIS JS API offline, but we don't officially support the workflows - you won't be able to call tech support if there are any issues. And, there are limitations on taking certain Esri basemaps, services and data offline using ArcGIS JS API. Fully supported and robust offline functionality is available for our Runtime SDKs and Desktop. I hope that helps.
